### ISSUE TITLE
Add landscape mode layout for Circle of Trust.

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#102]
Landscape mode layouts have not been added to CircleOfTrustFragment . Thus it uses the portrait layout file for landscape mode too, which looks like this -
![screenshot_2016-03-06-17-19-18](https://cloud.githubusercontent.com/assets/8321130/13553957/a8d89562-e3c0-11e5-9018-abee039f7fff.png)

Here we have to scroll down for viewing the rest of comrades and the idea of having a circle shown to the user is not fulfilled.I propose to add a separate layout file for landscape mode so that the entire circle appears on the screen in the landscape mode, just like the portrait mode.

**Comment by sandarumk** [comment]
Can you post a picture of what kind of change you are suggesting?

**Comment by yatna** [comment]
![screenshot_2016-03-09-19-51-09](https://cloud.githubusercontent.com/assets/8321130/13638233/5f4d225a-e631-11e5-970e-a550ac29ace6.png)

I changed a few dimens and restructured the layout a little bit to make the circle fit in the landscape mode

**Comment by sandarumk** [comment]
Hi Yatna, Thank you for reporting. Seems like this is a general issue. We will make this in the next development cycle, because of the UI changes may happen. I already created an issue for all the landscape issues and put on hold so we can revisit this in the future.

**Comment by sandarumk** [comment]
duplicated in #125
