### ISSUE TITLE
Show confirmation on exit without saving in Comrades' add numbers

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#103]
If the users add/edit Comrades' numbers from "Add the Comrade Numbers" screen and press back button on the device, it will navigate back to Circle of trust without saving the numbers. 
It will be more user-friendly design to show a confirmation dialog if the user adds/edits a number and try to go back without saving.

**Comment by sandarumk** [comment]
@calistus Please look into this.

**Comment by calistus** [comment]
@chamika The "OK" button at the bottom of that activity represents save. If a user edits a number without saving his action, it might be that the user was just playing around. So the change you are proposing is not necessary. Though we can rename that ok button to "save".

**Comment by sandarumk** [comment]
Then let's rename the button to save. @chamika you can do this and submit a PR

**Comment by sandarumk** [comment]
Merged
