### ISSUE TITLE
Duplicate comrade phone number 

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#106]
If the same phone number is given for multiple comrades then still update is being accepted and at a time multiple messages are sent to the same comrade

![screenshot_2016-03-07-00-11-58_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/14356938/13556192/7a6d47e8-e3f9-11e5-9990-9a18bc17c6e3.png)

Here, three messages are being sent at once to the same phone number 

Can I go ahead and implement this? @sandarumk

**Comment by sandarumk** [comment]
Yes you can go ahead with this

**Comment by sandarumk** [comment]
merged.
