### ISSUE TITLE
Grammatical error in Dialog Box

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#108]
![agqdpfm4uhrah6foplgzshwygukza4fgfknseq_8nsir 1](https://cloud.githubusercontent.com/assets/8949393/13561684/07a7039a-e456-11e5-87dd-3432c71ddc1a.jpg)

Also, can put a button which leads to Adding Comrades Activity on Dialog Box, since the user has intended to send help message

**Comment by ivan-claire** [comment]
I would like to solve this issue. Can I go ahead @rohands?

**Comment by sandarumk** [comment]
@rohands No need for putting a button to add comrades for now. But you are welcome to correct the error. What is the message you are intending to put?

**Comment by sandarumk** [comment]
@ivan-claire if you are interested in contributing, go through the READ ME and the wiki. The current open issues are all from our GSoC aspirants who are waiting for the confirmation from the team. You can also follow their path and set up the environment, build the project and find any issues and improvements in the currently developed sections.

**Comment by ivan-claire** [comment]
Thanks @sandarumk. I've already setup the environment and built the project. I'll start looking for issues and improvements.

**Comment by sandarumk** [comment]
Please read the previous issues (both open and closed) before you report an issue. They will give an idea about what kind of issues we expect.

**Comment by rohands** [comment]
@sandarumk 
Would "Failed to send message since no comrades have been registered" be fine?

**Comment by sandarumk** [comment]
Okay. You can go ahead with this.
