### ISSUE TITLE
Bug in Add Comrades Activity

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#109]
In Add Comrades Activity, if the user doesn't enter any comrade number and clicks on OK button, the current behaviour of the app is to exit the activity and go back to Circle of Trust Activity with the following message. 
"Comrade Numbers have been updated".
Even though none of the comrades have been registered.
This could be made more meaningful by prompting the user to add atleast one comrade. After which, the message "Comrade Numbers have been updated" could make more sense. 

Would this be considered as a valid issue?

**Comment by sandarumk** [comment]
Instead of prompting the user to add at least one comrade, can you make the said toast message appear only when comrades  are being updated. Use a different toast message when there is no change.

**Comment by rohands** [comment]
@sandarumk 
Can I have "No Comrades Registered" as the toast message for when there is no change?

**Comment by rohands** [comment]
@sandarumk 
I was working on this issue and I figured out that the implementation has to be on the lines of the following :
If the newly entered comrade numbers match the old ones, then I need a different toast message saying "no changes have been detected".
If not, the same message which is being displayed now, that "comrade numbers have been updated remains the same".

**Comment by sandarumk** [comment]
Merged
