### ISSUE TITLE
Adjust text sizes to make it readable on larger screens

### ISSUE THREAD

**Issue by AaskaShah** [systers/PCSA-Android#115]
Can I go ahead with this ?

**Comment by sandarumk** [comment]
Can you give more details with examples.

**Comment by AaskaShah** [comment]
The texts in the screenshots could be made bigger as space is there and would look good to read.
![screenshot from 2016-03-09 16 28 08](https://cloud.githubusercontent.com/assets/11875217/13633407/c8437948-e614-11e5-9826-98b6b88e35ea.png)
![screenshot from 2016-03-09 16 29 04](https://cloud.githubusercontent.com/assets/11875217/13633409/c9e02e5e-e614-11e5-80dc-b51264e022b0.png)
![screenshot from 2016-03-09 16 29 53](https://cloud.githubusercontent.com/assets/11875217/13633413/cd53f7fa-e614-11e5-8071-3c70b41d69f2.png)

**Comment by sandarumk** [comment]
Thank you for reporting. We will schedule this after the next sections are implemented in GSoC since this is an issue in general.
