### ISSUE TITLE
Modify instructions in READ ME file

### ISSUE THREAD

**Issue by ivan-claire** [systers/PCSA-Android#116]
The instructions on opening and running PCSA in android studio are not correct. 
Should I modify the instructions?

**Comment by sandarumk** [comment]
@Buddhiprabha Can you please check this issue

**Comment by Buddhiprabha** [comment]
@ivan-claire What are the changes you suggest?

**Comment by ivan-claire** [comment]
Here is what I suggest under Opening and Runnung 
**Opening and Running**
•	Launch android studio
•	Click on File, then New and then Import Project Or from the welcome screen of android studio click on Import project
•	Browse to the directory where you cloned (extracted the zip) PCSA-Android App and take OK
•	Let Android studio import the project, sync, run and build the Gradle. 
•	If Gradle finishes to build without error, connect your android phone and run the project by clicking on the play button on the tool bar
•	Now, Choose your device to run the project on from the dialog box that appears
•	Wait for a few seconds and the app should start on your device.

**Comment by Buddhiprabha** [comment]
@ivan-claire are you planning to complete this?

**Comment by sandarumk** [comment]
Merged #210
