### ISSUE TITLE
Floating Labels for EditTexts 

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#118]
![screenshot_2016-03-09-18-07-37](https://cloud.githubusercontent.com/assets/8949393/13635466/f0bae78c-e621-11e5-8f19-d66ed2d5b077.png)

The new EditText has Floating Labels like the one shown above for Comrade1, it looks better and it doesn't diverge from the expected design from the team. 
Can I go ahead implementing them for the trustees layout?
The above example doesn't have the contactpicker icon on it, I'll do it once the issue is accepted.

**Comment by calistus** [comment]
The floating design came up with the emergence of material design. We don't want to juxtapose design here. So we can only have a floating editText when we have a material look and feel.
