### ISSUE TITLE
ContactPostStaff needs to be fixed in Landscape mode 

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#119]
Didn't seem to notice this in my earlier PR, but the landscape mode of ContactPostStaff seems to be unsymmetrical. 
Needs to be fixed

![screenshot_2016-03-09-18-33-26 2](https://cloud.githubusercontent.com/assets/8949393/13636073/c85720cc-e625-11e5-9c61-4da8e9d1909e.png)

**Comment by sandarumk** [comment]
This seems to be a general issue, hence I created a general issue. We will revisit this, when the next development cycle starts.

**Comment by rohands** [comment]
@sandarumk 
I'd like to bring to your notice that I don't need to create another layout for landscape for this. The issue is with the android:weight property I've given.

**Comment by rohands** [comment]
@sandarumk 
Can I fix this issue, this only needs a change in the android:weight property and doesn't need another layout for landscape mode?

**Comment by sandarumk** [comment]
@rohands even if this is a small fix if the UI s gonna change (not sure yet) no need fixing this now. We will fix this all with #125

**Comment by rohands** [comment]
Is this a duplicate issue?

**Comment by sandarumk** [comment]
yes. We created another separate general issue for landscape improvements. We are going to handle that with the UI update.
