### ISSUE TITLE
No checking has been done for detection of network

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#120]
Steps to reproduce the issue : 
1. Put phone in airplane mode.
2. Go to Circle Of Activity
3. Try sending a message. 

Current implementation : 
Shows a dialog box which says
"Message sent to # number of registered comrades. "

Need to check for Network Detection

**Comment by sandarumk** [comment]
@calistus Can you look into this

**Comment by sandarumk** [comment]
@rohands What is the toast message you are hoping to add if the network detection fails?

**Comment by rohands** [comment]
Network Unavailable, Please try again later?

**Comment by PrabhanshuAttri** [comment]
@sandarumk Can I do this?

**Comment by sandarumk** [comment]
No you can't. Usually the issue belongs to the one  who reports it. You have to find your own issue and get it approved. For more information read the READ ME file. Read through the current and closed issues to avoid duplicating.

**Comment by sandarumk** [comment]
@PrabhanshuAttri May be I wasn't making myself clear. You can fix the issue when it is approved and if the student reported doesn't want to do it. Sorry I missed the "approved" part. Please read the README for more information.

**Comment by sandarumk** [comment]
@rohands Is this the only place which has not been checked for detection of network? Or is the other message sending places has the same issue?

**Comment by sandarumk** [comment]
@rohands One more question do you want to give this issue to @PrabhanshuAttri since he already submitted a PR. Sorry for my delay in approving the issue.

**Comment by rohands** [comment]
@sandarumk I'd like to do it myself. Sorry for the delay in the reply

**Comment by rohands** [comment]
@sandarumk Yes, this is the only place for the delay in the reply. I will submit a PR soon

**Comment by PrabhanshuAttri** [comment]
@sandarumk I didn't see any activity that's why I created the PR. @rohands No problem buddy. :)

**Comment by rohands** [comment]
@PrabhanshuAttri I think the team is soon going to come up with beginner issues as mentioned in #154. Maybe you can get started with those issues :)

**Comment by sandarumk** [comment]
merged.
