### ISSUE TITLE
No Phone Number Validation

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#121]
There is no validation for Phone Number in Trustees.java
Currently any number of digits is accepted as input. Since the mobile number is not displayed in Circle of Trusts Activity, the user at first glance will not know that he has made that mistake.
Need to validate in some way. I think, 10 digits is universally accepted.

**Comment by sandarumk** [comment]
This issue is previously been reported. There is currently ongoing discussion about this. Please go through the issue list first when you report the issues to avoid the duplicates

**Comment by sandarumk** [comment]
If you would like, yo can discuss the validation procedure in that issue.
