### ISSUE TITLE
Dialog Box disappears on changing configuration

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#122]
Steps to reproduce : 

1. Go to Circle of Trust
2. Click on Help Me Button
3. Dialog box appears, now turn to landscape, dialogbox disappears. 

It's possible to override some methods which keeps the Dialog Box intact

**Comment by rohands** [comment]
This is valid for dialog boxes of ContactPostStaff and ContactOtherStaff also.

**Comment by sandarumk** [comment]
Can you give me a detailed analysis on why this happens?

**Comment by rohands** [comment]
Whenever you turn your phone to landscape mode (a configuration change occurs) the activity is recreated and unless explicitly speicifed, the dialogbox which was open earlier won't be displayed again. 

To fix this you need to add 
android:configChanges="orientation"
and override onCreateDialog or onPrepareDialog.

Once you're done implementing this, your'll see that your dialog will also be recreated if configuration changes occur. The best part is that your Activity will manage your dialog for you. It will be reused when possible, reducing dialog load times if you perform heavy initialization.

**Comment by sandarumk** [comment]
You can go ahead with this.

**Comment by sandarumk** [comment]
Merged
