### ISSUE TITLE
Small grammatical error in CircleofTrust

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#124]
![screenshot_2016-03-09-21-21-44](https://cloud.githubusercontent.com/assets/8949393/13641060/258d0592-e63d-11e5-99d0-9ad47643aa82.png)

Need to check for singularity(noun)

**Comment by sandarumk** [comment]
How are you going to fix this in the code?

**Comment by vihanga-liyanage** [comment]
Please forgive me if I'm over stepping hear, but can't we use a simple if condition?

**Comment by rohands** [comment]
If you look into the code in CircleOfTrustFragment, there's a variable called counter which stores the number of registered users. 
All I need to do is just to check if the value of that counter variable > 1, then print "Comrades" in the end, or else print "Comrade"

@vihanga-liyanage yes, it's a simple fix.

**Comment by sandarumk** [comment]
Merged.
