### ISSUE TITLE
Force close issue in ContactPostStaff and ContactOtherStaff DialogBox

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#127]
If the user navigates to Reporting Process > Contact Staff To Report > Contact PCMO, the app will be force closed due to an exception on pre KitKat(API 19) devices. This affects every situation where the Dialog Box is showed. 

The cause for this issue is calling ListView.addHeaderView() after ListView.setAdapter().
As the addHeaderView() documentation describes

> Note: When first introduced, this method could only be called before setting the adapter with setAdapter(ListAdapter). Starting with KITKAT, this method may be called at any time. 

The issue can be fixed by calling addHeaderView() before the setAdapter() method call

**Comment by sandarumk** [comment]
Does this happens only in these dialog boxes or in every dialog box in contact post staff??

**Comment by chamika** [comment]
In every Dialog Box which shows the user to select Voice Call or Send Message will affect this.

**Comment by sandarumk** [comment]
Ok. You can go ahead and submit a PR.

**Comment by rohands** [comment]
@chamika @sandarumk 
It'll affect every dialogbox since the code to generate the dialog box is orthogonal with respect to the place where it's being called

**Comment by sandarumk** [comment]
I am guessing that this is not the same issue you were talking about earlier?
@chamika any comment on this? Is this the same readon for #122

**Comment by rohands** [comment]
@sandarumk 
No, it has nothing to do with it.

**Comment by chamika** [comment]
@rohands
This is not related to orientation changes

**Comment by rohands** [comment]
@chamika 
That's exactly what I said.

**Comment by sandarumk** [comment]
@rohands Isn't the dialog box being orthogonal is the reason for #122 ? How does it maps here?

**Comment by rohands** [comment]
@sandarumk 
I think there is some confusion here. Let me clarify
The issue #122 has nothing to do with this issue. Infact the code which creates the dialog box themselves are different in both these cases. 
This issue is based on the fact that on devices running < API 19 the call to addHeaderView should be done before the call to setAdapter as @chamika told us. 
And #122 is because of recreation of activity on configuration change. Let's not mix them.

**Comment by sandarumk** [comment]
@rohands I understood that these are too separate issues. But I couldn't get your comment. I earlier thought that you have confused with your issue with this. But later I figured it out that your comment was regrading your implementation of the dialog box. Sorry for the confusion.

**Comment by sandarumk** [comment]
mereged.
