### ISSUE TITLE
Unused Resource in the application

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#128]
Following xml files are not used in the app
R.layout.activity_circle_intro
R.drawable.bg_btn_arrow_showless
R.drawable.custom_bg_button_active
R.drawable.custom_bg_button_active2
R.drawable.custom_bg_button_normal
R.drawable.custom_bg_button_normal2
R.drawable.custom_bg_edit_text
R.drawable.custom_selector_button
R.drawable.custom_selector_button2

Following strings in strings.xml are not used.
Some of them are defined in strings.xml. But they are not used in layouts or source
R.string.hello_world
R.string.action_settings
R.style.pcsaAlertDialogStyle
R.string.reporting_get_help_foot1
R.string.reporting_get_help_foot2
R.string.title_activity_testing
R.string.helping
R.string.friends_and_community
R.string.learn_effect
R.string.bystander
R.string.predator_tactic
R.string.ok_button
R.string.slide_2_head
R.string.str_cnt_mnu_edit
R.string.str_cnt_mnu_share
R.string.str_cnt_mnu_delete
R.string.title_activity_get_help_now
R.string.hello_blank_fragment
R.string.comrade1_number
R.string.comrade2_number
R.string.confirmation_message

Unused color resources in colors.xml
R.color.Title_color
R.color.fragment_of_trust_text_color

dimens.xml
 R.dimen.layout_marginTop

informations.xml
R.array.locations

integer.xml
R.integer.zero

styles.xml
R.style.pcsaAlertDialogStyle

These resources should be removed or used properly at the appropriate places.

**Comment by sandarumk** [comment]
You can go ahead with this.

**Comment by sandarumk** [comment]
While you are at it, can you refactor these xml files as well. Because of the various patches, grouping has being little bit muddled. some names are not optimal.

**Comment by sandarumk** [comment]
Merged
