### ISSUE TITLE
Redundancy not required

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#134]
There are 2 instances of redundancy which can be removed.

One of them is at line number 222 in Trustees.java 
The call, 
<strong>phoneNumber.toString()</strong> is redundant because toString is being called on a String value itself. 

One more is at line number 185, there is no need to initialise the value of <strong>phoneIdx</strong> to be 0. This initialisation is useless. 

Also, in line number 153, there is no description for "@return", the return value of the function findInput()

**Comment by sandarumk** [comment]
There is a separate issue regarding the app comments. So you can leave the commenting issue to that. For time being. You can submit a PR with this and #133 . Please use minimum number of commits.

**Comment by rohands** [comment]
@sandarumk Sure. 
I also noticed that there are 3 more dialogboxes which are not getting recreated on landscape mode. I should have noticed this before my PR earlier. However I'll add them all (dialogboxes) into one commit so that you can revert to it incase of any bug.

**Comment by sandarumk** [comment]
Merged.
