### ISSUE TITLE
Implement 'Change Location' as in mockup

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#136]
The drop down can be made similar to the one in mockup
Also, we can add (current post) as given in mockup "This is information for Uganda (current post)"

![screenshot_2016-03-10-01-28-32_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/14356938/13648720/1da55424-e660-11e5-8424-939074ae1741.png)

![screenshot 505](https://cloud.githubusercontent.com/assets/14356938/13648726/2782bf9a-e660-11e5-9b3f-9183d2a543d9.png)

**Comment by sandarumk** [comment]
@Buddhiprabha Please look into this.

**Comment by sandarumk** [comment]
@Buddhiprabha What is the correct implementation of this. Is the implemented version correct or the mockup?

**Comment by Buddhiprabha** [comment]
You can add the phrase "current post"
_similar to the one in mockup_ - what are the changes you suggest?

**Comment by AkankshaBodhankar** [comment]
@Buddhiprabha The look can be enhanced by adding a border to the drop down or something similar can be done

**Comment by Buddhiprabha** [comment]
Okay. In addition to adding the phrase, change font color to white with a white border and white dropdown icon.

**Comment by AkankshaBodhankar** [comment]
Yes will do it soon :-)

**Comment by sandarumk** [comment]
Any updates on this?

**Comment by AkankshaBodhankar** [comment]
Sorry! I'm running a bit late but its in progress just adding the icon to correct place is creating some problem will do it ASAP

**Comment by AkankshaBodhankar** [comment]
PR sent #226
