### ISSUE TITLE
Duplicate comrade phone number when picked from contacts

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#137]
When the same contact is picked twice it is accepting duplicate comrade numbers
The duplicate comrade numbers is checked only if typed manually not when picked from contacts
Here the number appearing twice is picked from contacts one after the another 
![screenshot_2016-03-11-15-59-01_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/14356938/13699776/954fe320-e7a2-11e5-8223-a2acee7e7511.png)

**Comment by AkankshaBodhankar** [comment]
@sandarumk can i go ahead and implement this

**Comment by sandarumk** [comment]
yes you can go ahead with this.

**Comment by AkankshaBodhankar** [comment]
PR made #157

**Comment by AkankshaBodhankar** [comment]
PR made #177
