### ISSUE TITLE
Alert the user regarding no balance amount in phone account

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#138]
The user must be alerted that there is no balance amount in the phone account to send messages through the application.
This can happen in the prepaid mobile phones
If the user has no balance amount the messages to be sent will be failed 
But, it will give the user false notion that message has been sent due to the following alert

![screenshot_2016-03-11-16-08-56_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/14356938/13699931/a75f11d4-e7a3-11e5-98e1-a5591989e2b2.png)

**Comment by Buddhiprabha** [comment]
If there is a false notification indicating that the SMS has been sent, it needs to be fixed. @calistus Please check this..

**Comment by calistus** [comment]
@AkankshaBodhankar  You can handle this and send a PR

**Comment by AkankshaBodhankar** [comment]
@calistus Thank you Will make a PR soon :-)

**Comment by sandarumk** [comment]
Any updates on this? By the way what is the method you are going to use for this? Are you going to monitor the account balance ? How are you hoping to do that? Or else are you going to detect the sending fail of the message and then gives a toast saying the message is sent?

**Comment by AkankshaBodhankar** [comment]
@sandarumk I referred to the issue #161 and the discussion going on there. I thought it would be better to wait. I had an idea in mind regarding implementing this
We can check for the balance at fixed time intervals (say daily once or hourly or so)
Then, if it is below Rs.5 (or limit of balance according to the currency of country - this also needs to be discussed as we can't alert the user when account has 0 amount, it wont be helpful in emergencies. It will be better if we have keep a limit like if its less that Rs.5 or something)

**Comment by sandarumk** [comment]
The issue you are referring is closed. I closed that because you are handling the no balance amount and rohan has already taken care of the network. What to be fixed here is the incorrect toast message as @Buddhiprabha mentioned. 
Before going forward on this discussion, my question is how are you going to monitor the balance (that the current balance is X)?

**Comment by AkankshaBodhankar** [comment]
I didn't find any such API which does the same. I'm sorry for the wrong interpretation. Just we need to check if message has been sent or not. Getting the phone balance is not possible 
But however there are alternatives like: 
1.when message sending is failed we can give a toast or message saying that amount might be the problem
2.we can also provide an option to make a call to service provider which gives the balance (however, this requires every provider number again)

**Comment by sandarumk** [comment]
Second option will not work because of the multiple service provider in different countries. However the first one seems feasible. But I guess you can't explicitly detect that the reason behind the fail is the balance. So if you are going to implement this, keep a general toast message saying that the message sending failed.

**Comment by AkankshaBodhankar** [comment]
@sandarumk yes will do that and make a PR soon

**Comment by sandarumk** [comment]
@AkankshaBodhankar Are you working on this? If not we can give this to some one who can since it has been 20+ days since you claimed this

**Comment by rohands** [comment]
Sure, I'll look into this issue.

**Comment by AkankshaBodhankar** [comment]
Yes that would be okay to assign it to someone else

**Comment by rohands** [comment]
@sandarumk
I'd like to take this issue up if possible

**Comment by sandarumk** [comment]
sure.

**Comment by sandarumk** [comment]
Solved visa SMS Failure detection.
