### ISSUE TITLE
Display the names of the comrades above the avatars in the Circle Of Trust

### ISSUE THREAD

**Issue by prafful002** [systers/PCSA-Android#141]
If the user wants to quickly view her current list of comrades it is not possible since there is no way for the user to view the names of the comrades. Even on the Add Comrades screen, only the phone numbers are being displayed. The names of the comrades should be displayed (preferably above the avatars) in the circle of trust.

**Comment by sandarumk** [comment]
This issue is being reported, even there were PRs as well. Please go through the open and closed issues in the issue list before you report an issue. Please read the READ ME as well.
