### ISSUE TITLE
'Edit Info' screen shows keypad on opening

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#142]
On clicking the edit comrade button, the following screen shows up.
![screenshot_2016-03-12-00-53-13](https://cloud.githubusercontent.com/assets/8321130/13713232/fd4013ce-e7ed-11e5-9099-7cab9f093955.png)

Here, the keypad opens up automatically hiding the 6th comrade and the save button . Therefore,the user has to click the back button to view the entire the entire screen.
What I suggest is that , on clicking the edit button the following screen should show up. The keypad must only appear when the user explicitly clicks on any comrade.
![screenshot_2016-03-12-00-53-28](https://cloud.githubusercontent.com/assets/8321130/13713308/635bd8dc-e7ee-11e5-97b0-819a7dc59217.png)

**Comment by sandarumk** [comment]
hi Yatna, you can go ahead and submit a PR combining all the issues you reported in edit info scree. Next time when you are reporting issues, please use one issue to report all the bugs in the same screen. (Unless they require a significant change). #143 #144  (you should have reported #143 and #142 as one issue). please use minimum number of commits and meaning full commit messages.

**Comment by sandarumk** [comment]
Merged.
