### ISSUE TITLE
Opening 'Edit Info' Screen shows cursor at wrong place.

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#143]
Opening Edit Info Screen shows up the following -
![screenshot_2016-03-12-01-13-51](https://cloud.githubusercontent.com/assets/8321130/13713584/b8edfc02-e7ef-11e5-807c-0d13a8e46d42.png)
Here the cursor is automatically placed at the beginning of the first comrade's contact number, which is not desired.
Along with removing the keypad as suggested in #142 , I think the cursor should only appear when the user explicitly clicks on any comrade's EditText.

**Comment by AkankshaBodhankar** [comment]
I think this issue is to be closed. Just to avoid confusion if it has to be solved or not

**Comment by yatna** [comment]
This issue has been solved .
