### ISSUE TITLE
Display edited contact with a different shade

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#144]
In the 'Edit Info' screen, sometimes it becomes confusing for the user to know which contact is edited and which contact is the same as  earlier. This happens because all numbers whether edited or not are shown with the same color. This is more prominent when multiple contacts are edited.

This can be avoided by using a lighter shade of black for displaying the numbers which are being edited. Thus the user can clearly identify the contacts, which are being modified.

**Comment by sandarumk** [comment]
Merged.
