### ISSUE TITLE
Names of comrades not taken as input from the user

### ISSUE THREAD

**Issue by AaskaShah** [systers/PCSA-Android#145]
The names of the comrades are not taken as input from the user and not stored in the application. The contact numbers could be stored with the corresponding comrade names so that during updating the list, user could get aware of which comrades are registered. Identifying with contact numbers gets difficult.

**Comment by sandarumk** [comment]
Thank you for reporting. There were menu issues reported even earlier to add the names. But the current approved UI doesn't support this. We will take this into account when the UI designing happens for the next version.
