### ISSUE TITLE
Allow the user to send message to comrades through other messaging apps (like WhatsApp, Telegram)

### ISSUE THREAD

**Issue by prafful002** [systers/PCSA-Android#146]
In the circle of trust on clicking the Help Me button, the user must be given a choice to choose the messaging app through which she would like to send the message.

**Comment by AaskaShah** [comment]
The messaging applications like WhatsApp and others needs Internet connectivity too in both the sender and comrades' phones, which would not help at the times of need. Even if sender is connected to Internet, if comrades are not connected, the sender would be unable to know if his/her message has been delivered.

**Comment by prafful002** [comment]
When the sender has insufficient account balance but has access to the internet (open Wi-Fi is available in most public places) wouldn't this be a better way to communicate ?

**Comment by AaskaShah** [comment]
Yes ,but how will the user get assurance that his/her message has been delivered (what if none of the comrades' have internet connectivity) and will get help?

**Comment by sandarumk** [comment]
@prafful002 Thank you for your suggestion. We add this to the suggestion list and discuss with peace corps about the necessity of having such a feature.
