### ISSUE TITLE
The reporting types view issue in horizontal scrollviews

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#149]
The issue in the following view. 
Reporting Process >  Reporting Types
![screenshot_2016-03-12-15-48-08](https://cloud.githubusercontent.com/assets/754909/13722425/85fab85e-e86b-11e5-92a5-5f0f97b23a6f.png)

The horizontal scrollview is not suitable as a UI practice.

Solutions
1. Use ViewPager for horizontal scrolling. Only one set of steps will be visible at once. This will not adapt to the current UI.
2. Using arrow button similar to Get Help Now Post staff page.

**Comment by sandarumk** [comment]
@Buddhiprabha Can you look in to this

**Comment by sethbrudee** [comment]
i also noticed this.
Please, has this been fixed, or may i fix it?

**Comment by sandarumk** [comment]
@sethbrudee We are waiting for the @Buddhiprabha 's approval on this.If approved, if the reported contributor do not want to fix this you can fix.

**Comment by Buddhiprabha** [comment]
@chamika It was a design decision to have the types in this way. Both types should be visible at the same time. If you can optimize the code, do so, but do not change the design to be similar to that of Post Staff. Sorry about the delay in reply.
