### ISSUE TITLE
Add a README file for PCSA

### ISSUE THREAD

**Issue by Buddhiprabha** [systers/PCSA-Android#15]
Add a proper README file for PCSA.

**Comment by sarayd** [comment]
Hi @Buddhiprabha , may I claim this to do as a GCI task?

**Comment by Buddhiprabha** [comment]
@sarayd Yes. The GCI task is available at https://codein.withgoogle.com/tasks/6390384649306112/?sp-organization=5748107203575808. Please claim and start working.

**Comment by sarayd** [comment]
Hi I would like to claim this task, thanks!

**Comment by Buddhiprabha** [comment]
Resolved by the PR https://github.com/systers/PCSA-Android/pull/20
