### ISSUE TITLE
Requesting runtime permissions for Android M

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#160]
Quoting developers.android.com,
<blockquote>
<p>
On all versions of Android, your app needs to declare both the normal and the dangerous permissions it needs in its app's manifest.<br />

- If the device is running Android 5.1 or lower, or your app's target SDK is 22 or lower: If you list a dangerous permission in your manifest, the user has to grant the permission when they install the app; if they do not grant the permission, the system does not install the app at all.<br/><br/>

- If the device is running Android 6.0 or higher, and your app's target SDK is 23 or higher: The app has to list the permissions in the manifest, and it must request each dangerous permission it needs while the app is running. The user can grant or deny each permission, and the app can continue to run with limited capabilities even if the user denies a permission request.
</p>
</blockquote>

Looks like Android Manifest file needs some changes. 
Before sending message in CircleOfTrust, I think we should mention using sms feature as a dangerous permission in the manifest.

**Comment by yogeshbalan** [comment]
I claim this issue. I will add add the popup dialog requesting permission to send sms before sending sms in Android M devices.
Thanks

**Comment by sandarumk** [comment]
Hi yogeshbalan, The issue usually belongs to the one who reports the issue unless it is not from a community member. Please go through the README first. You have to find your own issues, report them, once they are approved, you can work on them. There is a wiki too. Before you report, go through the closed issues as well to avoid duplicates

**Comment by yogeshbalan** [comment]
Okay sandarumk. Thanks for helping. I will keep that in mind.

**Comment by rohands** [comment]
@sandarumk Any updates?

**Comment by rohands** [comment]
@sandarumk Can I proceed?

**Comment by sandarumk** [comment]
The circle of trust should send the message using a single click because it is being used in extreme circumstances. Therefore adding another button click should be stopped. So what should be done is taking the permission when the user installs it. What is the current behavior of Android M in this case? It should be similar to the older versions. If not you can fix that

**Comment by rohands** [comment]
<code>SEND_SMS</code> is classified as a dangerous permission. If listed in the manifest file, the system will <strong>NOT</strong> grant this permission directly during installation. Hence, the user can grant/decline this permission. So the point is the system doesn't grant the permission during installation.
But again, all this would matter only if the target SDK is set to 23 or higher. The current target SDK is at 22. So, it does not matter. All the permissions mentioned in the Android Manifest file are granted during the installation of the app itself.
This could be a serious concern during the later stages of development of the app (setting target as 23) 
For now, nope no issues.

**Comment by yogeshbalan** [comment]
The best practice, IMO is to lower the **targetSdkVersion** to 21, and android will do the rest.

**Comment by rohands** [comment]
@yogeshbalan the problem is with <strong>targetSdkVersion</strong> 23 or higher. The current implementation (22) will not pose any problems.

**Comment by sandarumk** [comment]
http://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en 
This will solve all the problems you are having. So since our target version is 22 we do not have any problem as rohan said. So there is no need of worrying this for now . So I think there won't be any changes necessary in the manifest file as you mentioned in your issue right @rohands .

**Comment by rohands** [comment]
@sandarumk yes, no problem in the current implementation.

**Comment by sandarumk** [comment]
So we will keep this as it is. If we make our target version higher, we will revisit this. But for the time being this is not necessary.
