### ISSUE TITLE
No callbacks registered while sending sms

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#161]
In the current implementation, there hasn't been any listeners registered to know if the message has been successfully sent or not. 
<a href="http://stackoverflow.com/questions/18771356/check-if-an-sms-is-actually-sent">Link to implementation</a>
The above link suggests how we can listen for events by which we can conclude if a message is actually sent. 

There are certain issues which could arise because of the above mentioned functionality which is missing in the current implementation. 

Steps to reproduce - 
1. Use a dual sim phone
2. In your preferences, set your options such that, every time when you are sending SMS, Android asks you which SIM to choose (actually, it's set by default unless you have changed it before)
3. Now go to Circle Of Trusts, and click on one of those three messages.

What happens is this - 

You get a dialog box saying "Message has been sent to # no of registered comrades".
And on closing the dialogbox, you see an option to choose which SIM to send the message from.

So, the message hasn't been sent yet, but the current implementation shows message has been sent. 
Clearly, an implementation bug. 
Solution is to register handlers and move the dialogbox code within that. Can I work on this?

**Comment by rohands** [comment]
Also, try entering a wrong number and send the message.
The current implementation doesn't tell the user, the message failed to send.

**Comment by rohands** [comment]
@sandarumk @Buddhiprabha please look into this issue.

**Comment by rohands** [comment]
@sandarumk Can you please approve this issue so that I can implement it?

**Comment by rohands** [comment]
I failed to mention this earlier while opening the issue. There's another loophole here. If the user has given a wrong number for Comrade, then the current behavior indicates that the message is successfully sent. So, by fixing the current issue, it will take care of the above mentioned loophole too.

**Comment by Buddhiprabha** [comment]
I hope this solves https://github.com/systers/PCSA-Android/issues/138 as well? @calistus please check this.

**Comment by rohands** [comment]
@Buddhiprabha Yes, it does.

**Comment by rohands** [comment]
@calistus Could you please review this as well?

**Comment by rohands** [comment]
@Buddhiprabha can I proceed?

**Comment by Buddhiprabha** [comment]
@calistus Please confirm. @rohands Please discuss with @AkankshaBodhankar too as this addresses an issue reported by her previously.

**Comment by calistus** [comment]
Let @AkankshaBodhankar handle the checking of account balance(since she reported that before you) while you handle the remaining issues you just reported(i.e confirming that the message was successfully sent and checking that real phone numbers are entered )

**Comment by rohands** [comment]
@calistus Thank you for clarifying the issue. Yes, I shall go ahead fixing the bugs

**Comment by AkankshaBodhankar** [comment]
@calistus Will work on it and fix it as soon as possible

**Comment by rohands** [comment]
@calistus @sandarumk @Buddhiprabha 
I feel that we need more discussion regarding this feature (checking if SMS was sent or not) 
Since the users will press the <strong>Help Me</strong> button only during cases of emergency, a toast message appearing that "SMS failed to send" at those times (that too, not instantly) doesn't really serve the purpose. 
I feel that we should check whether the SMS can be sent to the numbers which are registered during the time of the registration itself by sending test SMS to the number. By doing this, we can check if the number is a real phone number or it is wrong. 
Other issues which could arise during the emergency time are "no balance amount" and "no network" . @AkankshaBodhankar is taking care of "no balance amount" and I have previously taken care of network detection. 
But again, informing the user about this during times of emergency is not the way to go, I feel. 
Maybe we should warn them before? For example, whenever the person is entering a place which is barred of network, we should alert the user that they cannot use the app to send message to their comrades. By doing so, the user will want to be more careful.

**Comment by AkankshaBodhankar** [comment]
@rohands Yes i agree with you too

**Comment by rohands** [comment]
@sandarumk Kindly let me know what is the best way I can fix this issue? I have mentioned my thoughts above in this thread

**Comment by sandarumk** [comment]
I agree with your idea of sending a test message. But it needs further discussion with peace corps. What I can do is, I can tag this as a suggestion so we can revisit this. Warning the user every time when the user enters a no network area might not be the best way to get around this. But we can have a further discussion on this when the next sprint starts. Since validating numbers and checking network is already done, I am closing the issue.

**Comment by yogeshbalan** [comment]
IMO, the solution for above two problem mentioned by @rohands and @AkankshaBodhankar would be to create a background service. 
The service will always run in the background and will do following tasks : - 
 - Check balance after every finite interval of time (A notification will appear of current balance is less than some threshold value
 - Check spaces in phones numbers which are assigned as comrades. (also if the phone no. is changed in contacts app, there should be a functionality to update comrades phone no inside app. I will create a separate issue if this use-case is not mentioned before.)
- Notify user about network connection after every finite interval of time.
- Alert user if network connections gets lost

P.S : I can work on this solution if allowed by @sandarumk @Buddhiprabha @calistus . Thanks :)

**Comment by rohands** [comment]
@yogeshbalan I'd like to make it clear that I was waiting for an appoval to fix the issue. I guess you're not accustomed to the process of contributing which the project follows. I would request you to please take a look at the README file once

**Comment by rohands** [comment]
@yogeshbalan The issue was not about how to implement. What I was trying to make clear is whether I should check for balance and alert the user about network validation before itself. Implementation, in a very obvious way would be use to Service. You might have misunderstood my "Kindly let me know what is the best way I can fix the issue", just making it clear.

**Comment by sandarumk** [comment]
@yogeshbalan As i said in the Rohan's issue notifying the user when the network get lost may not be the best way to implement this. The service you are suggesting will only add additional overhead to the app. Monitoring the balance and the network connection is not the purpose of this app.

**Comment by yogeshbalan** [comment]
@sandarumk , I get your point. I think I need to look more closely to this issue to propose any suggestion further.
