### ISSUE TITLE
Dynamically add views in Add trustees

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#162]
![screenshot_2016-03-14-21-22-46](https://cloud.githubusercontent.com/assets/8949393/13750357/204db120-ea2b-11e5-9b02-8ac7535e1638.png)

This is how it has been currently implemented.
As you can observe, we are allowing updation of phone numbers in this manner, there is no specific order in which the users are adding trustees. 
So we could solve this by dynamically adding views like this,
For example, initially it could look something like this, 

![screenshot_2016-03-14-21-18-45](https://cloud.githubusercontent.com/assets/8949393/13750436/701ad70a-ea2b-11e5-8805-398a76f6b83d.png)

And then on changing the text in the 1st Comrade, dynamically a new view can be updated on the same layout to look something like this, 

![screenshot_2016-03-14-21-16-04](https://cloud.githubusercontent.com/assets/8949393/13750464/8b4b85a6-ea2b-11e5-9834-338193a2d831.png)

Further, 

![screenshot_2016-03-14-21-16-44](https://cloud.githubusercontent.com/assets/8949393/13750482/9fc1119a-ea2b-11e5-90dc-03d0626d1d64.png)

And then finally ... 

![screenshot_2016-03-14-21-17-50](https://cloud.githubusercontent.com/assets/8949393/13750494/abefd1c2-ea2b-11e5-9303-aa502db8d674.png)

**Comment by enuilin** [comment]
Hi there, dropping a note to say I'm working on this. The following use case occurred to me, though:

1) User creates 6 comrades.
2) User deletes comrade 4.
--> Does box 4 disappear? Or do we prevent the user from erasing 4 (forcing them to erase 6 and work their way back up)

The second solution is very clunky from the user perspective. I think I might actually rewrite the page to generate the edittexts dynamically, which would allow more flexibility. Should have a fix up in the next day or so.

**Comment by enuilin** [comment]
[Pull request up here](https://github.com/systers/PCSA-Android/pull/164)

**Comment by rohands** [comment]
@enuilin I guess you aren't accustomed to the way in which you report issues about the project and fix the same. 
Please read the README and you'll know that the person who opened the issue is only responsible for fixing the issue and making the PR. 
I'm sorry about this but this is the procedure. 
You're welcome to open new issues and fix them.

**Comment by enuilin** [comment]
Oh! I understand. Sorry about that!

**Comment by enuilin** [comment]
Hi! Okay, so I would just like to clarify some things from the README. It says [here](https://github.com/systers/PCSA-Android) that "If you want to contribute to PCSA-Android, subscribe to our systers-dev mailing list and shoot an introductory email. Pick an open issue from the issue list claim it in the comments, fix the issue and send us a pull request." I didn't do the first part (sorry about that!) but I'm a little confused about the second. Is there a special tag to differentiate open issues from closed ones? I see in the next line not to claim issues that someone else has been assigned to, but I didn't see an assignee on this issue so I thought it was okay to take this one. I apologize if I stepped on any toes, but I would just like to get the process as clear as possible so I don't do this again. Thanks!

**Comment by rohands** [comment]
Steps to contribute : 
1. Find a bug in the app or any modification that you'd like to suggest.
2. Open the issue
3. Wait for approval
4. If approved, fix the issue and make a PR.
This is how it works.

**Comment by rohands** [comment]
Regarding your queries, 
You can also pick an issue from the "opened" issues list, and "claim" it. Which means you should ask for approval, I guess. 
And by default the person who has opened the issue becomes the assignee unless otherwise specified. 
Maybe @sandarumk @Buddhiprabha will clear your doubts better

**Comment by enuilin** [comment]
So if I'm understanding this correctly, "open" issues have to be opened specifically by the creator to general fixing, right? I see. Thanks for clarifying!

**Comment by sandarumk** [comment]
@enuilin Thanks for bringing the fact that the READ ME has problems. I will update it to add more clarity.

**Comment by rohands** [comment]
@sandarumk I haven't got confirmation on this issue yet

**Comment by sandarumk** [comment]
I am holding up this issue because I sense a design update will soon change this page and its functionalities. So we do not need to make this now. We can do it with the update.

**Comment by rohands** [comment]
Oh okay, can you also please review the following issues #161 and #160 
I'll fix these issues and make a PR soon

**Comment by sandarumk** [comment]
@rohands Please refrain from mentioning your issues with unrelated issues because when you do that, it creates a link to an completely unrelated issue (which is mentioned in both places). It is a bad practice. Please link the issues if its important to do so and if you think the issues are related. For requests to reviews please use the said issue or slack channel #pcsa

**Comment by rohands** [comment]
Oh okay, I shall keep that in mind. Thank you

**Comment by sandarumk** [comment]
There was a similar previous issue of re arranging the numbers as well. We may have priorities implemented in future. So for the time being tagging this as a suggestion and closing the issue.
