### ISSUE TITLE
Inform user to add comrades if no comrades are present

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#163]
When user opens the 'Circle of Trust' - The application will check for count of comrades added. If this count is zero the user will be alerted to add numbers

![screenshot_2016-03-17-21-42-37_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/14356938/13852854/2100fbc0-ec8a-11e5-9a96-1ec6ee36f749.png)

**Comment by sandarumk** [comment]
We do not need this currently. However we will keep this in mind when we restructure the app in GSoC.
