### ISSUE TITLE
Number of comrade at the circle of trust is not verified

### ISSUE THREAD

**Issue by mari-linhares** [systers/PCSA-Android#165]
A verifier can be easily made using [regex](http://stackoverflow.com/questions/6960596/example-of-a-regular-expression-in-jquery-for-phone-numbers).
And invalid contact number such as: 111, 1, 2, 3 would not be accepted.

**Comment by rohands** [comment]
This is a duplicate issue.

**Comment by sandarumk** [comment]
There is an ongoing conversation on that. May be you can join there.

**Comment by mari-linhares** [comment]
Okay, thank you
