### ISSUE TITLE
comrades hard coded at Trustees.java

### ISSUE THREAD

**Issue by mari-linhares** [systers/PCSA-Android#167]
I was wondering if instead of objects defined individually I could create a list of contacts in order to avoid code repetition.

For example: 
  //Retrieving stored values
                old_comrade1 = sharedpreferences.getString(comrade1,"");
                old_comrade2 = sharedpreferences.getString(comrade2,"");
                old_comrade3 = sharedpreferences.getString(comrade3,"");
                old_comrade4 = sharedpreferences.getString(comrade4,"");
                old_comrade5 = sharedpreferences.getString(comrade5,"");
                old_comrade6 = sharedpreferences.getString(comrade6, "");

Now would be something like:

             for(in i = 1; i <= NUMBER_OF_COMRADES; i++)
                    old_comrade[i] = sharedpreferences.getString(comrade[i], "");

**Comment by sandarumk** [comment]
You can go on and make it.

**Comment by sandarumk** [comment]
@mari-linhares If you want you can make this since the PR mentioned above is rejected. If you are not going to make it, please comment so that I can add the tag "free" so that anyone else can claim it and work on it.

**Comment by mari-linhares** [comment]
Ok then, I'll do it. Thanks!
Em 28/03/2016 01:09, "Dinu Kumarasiri" <notifications@github.com> escreveu:
