### ISSUE TITLE
A Splash screen and logo can be added.

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/PCSA-Android#169]
A screen can come up just after the launch of application which will consist of a logo of the applications and the Official logo of Peace Corps. This will enhance the user experience.

**Comment by sandarumk** [comment]
This is a duplicate issue reported in https://github.com/systers/PCSA-Android/issues/49 When you are reporting issues and submitting the PR please go through the procedure which is defined in READ ME file.

**Comment by fatimarafiqui** [comment]
Okay. I will keep that in mind. Thanks.

**Comment by fatimarafiqui** [comment]
![screenshotsplash](https://cloud.githubusercontent.com/assets/13470643/13987465/af93f1ba-f12d-11e5-8331-5ea9b671fa5d.jpg)
This is the splash screen and the logo i made. Just in case you wish to use it.

**Comment by sandarumk** [comment]
Please go through the mockup video. It has the splash screen which is currently designed to have.
