### ISSUE TITLE
Display ripple effect when get help sms is send

### ISSUE THREAD

**Issue by PrabhanshuAttri** [systers/PCSA-Android#173]
We can show ripple effects on the get help screen while sending the sms, just like the shareit app.
![IMG](https://cloud.githubusercontent.com/assets/4739486/13985896/694de934-f125-11e5-8507-3101bff44f79.gif)

**Comment by sandarumk** [comment]
Hi Prabanshu, Can you describe the rationale behind why we need this?

**Comment by PrabhanshuAttri** [comment]
Just a suggestion to enhance user experience. :)

**Comment by sandarumk** [comment]
Does this blocks the current screen until the message is sent?

**Comment by PrabhanshuAttri** [comment]
No, it doesn't do that. The screen remains the same until get help button is pressed. Once pressed this animation can be shown for few seconds to keep the user updated about what's happening regarding the action she did. It's just one of the rules of UX/UI.

**Comment by sandarumk** [comment]
We will keep this as a suggestion and discuss this in the design meetings with Peace corps. Thank you for your reporting.
