### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by sethbrudee** [systers/PCSA-Android#176]
Making use of global variables in cases where local variables can be used. In Java, global variables are allocated more memory(heap memory) than local variables(stack memory). Therefore, using global variables increases the size of the application, which is meant to be minimized as possible.

Cases where some (not all) global variables, that can be replaced with local variables, in the code are:
ContactOtherStaff.java
ContactPostStaff.java
HomeScreen.java
OtherStaffContent.java
Steps.java
Types.java
CircleOfTrustFragment.java
Trustees.java

May I fix this?

**Comment by sandarumk** [comment]
Can you give some examples on the places where the code has global variables instead of local variables?

**Comment by sethbrudee** [comment]
For example, in ContactOtherStaff.java, lines 20 - 24 declares global variables which is better declared as a local variable. Same applies to HomeScreen.java, lines 19 - 23.

**Comment by sandarumk** [comment]
Yes you can fix this and submit a PR

**Comment by AkankshaBodhankar** [comment]
I think this issue is good to be closed. Just to avoid confusion
