### ISSUE TITLE
provide touch feedback in circle of trust fragment

### ISSUE THREAD

**Issue by yogeshbalan** [systers/PCSA-Android#182]
I user clicks on **EditButton/ResetButton** + **Help me button** in **CircleOfTrustFragment**, there is no touch feedback that will let user know that he/she had touched that button. Feedback can be in the form of **ripple** or **color/drawable** change of respective button. It is better to provide touch feedback to this fragment

**Comment by sandarumk** [comment]
Edit button do not need touch feedback because when you click the button you will be redirected to a separate page. 
@calistus, @Buddhiprabha do you agree or do you have another perspective.

**Comment by Buddhiprabha** [comment]
Yes I agree with @sandarumk 's suggestion. Please proceed.

**Comment by yogeshbalan** [comment]
The **"Help me"** drawable can be poped-up on click, assuring user that he/she has clicked it.
Also the weight of **"Help me"** button should be increased as it is covering very low volume in user's smartphone screen. The clicking of **"Help me"** is crucial in a case where user is engaged in an assault. It must occupy most of the screen space

**Comment by yogeshbalan** [comment]
![In App NOW](https://cloud.githubusercontent.com/assets/6052857/14233833/f6d35e5a-f9f0-11e5-9dc1-7def46654366.png)
![Increased Weight](https://cloud.githubusercontent.com/assets/6052857/14233834/f6d52488-f9f0-11e5-9b35-66c8073bc2e0.png)

**Comment by yogeshbalan** [comment]
@sandarumk can you please suggest whether I should send a PR for highlighting **HELP ME** or I should wait for further discussion.

**Comment by sandarumk** [comment]
Since we are going for a UI change in near future, you have to wait for he further discussion.

**Comment by yogeshbalan** [comment]
Okay. :+1: :)

**Comment by sandarumk** [comment]
Any update on the touch feedback of the Help Me button?

**Comment by yogeshbalan** [comment]
@sandarumk I could provide touch feedback to **Help Me** button by changing state of background drawable.
Can I send a PR for this?
I will Update a screenshot before sending PR if allowed.

**Comment by sandarumk** [comment]
Yes please do so.

**Comment by yogeshbalan** [comment]
Normal state
![screenshot_20160413-190547](https://cloud.githubusercontent.com/assets/6052857/14494933/fd6a3c68-01aa-11e6-8e19-c10b8256aa0a.png)
Pressed state
![screenshot_20160413-190551](https://cloud.githubusercontent.com/assets/6052857/14494934/fd71a868-01aa-11e6-9c87-d0c1e93b8b42.png)

Can I make a PR

**Comment by sandarumk** [comment]
Sorry I misunderstood you earlier. you are not suppose to change the button. You should only add the touch feedback.

**Comment by yogeshbalan** [comment]
Okay :+1:

**Comment by sandarumk** [comment]
Sorry. I misunderstood. I though you were going to add the touch feedback (vibration) to the button. But I just went through what you have suggested. The thing is you are not suppose to change the look of the app. Adding a ripple effect will also not add any value since the help me will give you a dialog box. Can you make the button to give heptic feedback?

**Comment by yogeshbalan** [comment]
Yeah definitely. I get your point. I am adding a vibration and ringtone event when **Help Me** is clicked.
Would it do?

**Comment by sandarumk** [comment]
Before you start on this please do some research on how it can be implemented and what is the impact on the permissions. I believe it would need vibration permission.

**Comment by yogeshbalan** [comment]
I will come up with all the details shortly. Then can I send the PR to resolve issue #234 because that needs to fixed ASAP as you mentioned.

**Comment by sandarumk** [comment]
No ringtone event. just add the heptic feedback.

**Comment by yogeshbalan** [comment]
Okay adding only heptic feedback on user clicking **Help Me** button.

**Comment by sandarumk** [comment]
1. That is a separate bug. Do not do cross references since once you reference it form a completely unrelated issue, it will create a link.
2. Since that is a separate one it should be fixed separately.

**Comment by sandarumk** [comment]
Merged
