### ISSUE TITLE
Use Fragments instead of activities.

### ISSUE THREAD

**Issue by yogeshbalan** [systers/PCSA-Android#183]
All the functional work should be done inside **Fragments** and **Activities** should only be used to handle and manage fragments. Fragments take much less memory than activities. 
 
For instance, inside **Reporting Process** Activity all the further screens can easily be managed by **Fragments** instead of using **Activities**. It will surely make app work faster and use less memory.

All for better readability we can switch to use viewpager slides in many place if we convert activities into fragments.
For instance, **Reporting Procecss** -> **Reposting Types** , the content inside contains two textview stucked in same activity. Two slides can be implemented to provide better readability. 

Well, according to Google's lectures (maybe [here](https://www.youtube.com/watch?v=amZM8oZBgfk)),   we should consider using Fragments whenever it's possible, as it makes your code easier to maintain and control.

**Comment by sandarumk** [comment]
Hi yogesh, Thank you for your suggestion. We are currently looking into this. And there are some previous issues reported suggesting similar changes like view pager sliding and adding fragments as well. We have a major design and UI update coming with the next development where we are going to focus on these type of suggestions.

**Comment by rohands** [comment]
@sandarumk I believe this issue has also been resolved. I have changed everything to fragments. Is it time for this to be closed?

**Comment by sandarumk** [comment]
@rohands Let's keep this and other on hold issues open until the GSoC finishes. Then we will go through the app and close the fixed issues.

**Comment by sandarumk** [comment]
Fixed.
