### ISSUE TITLE
App has a build issue due to missing import

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#185]
Unable to build the application due to missing import in the com.peacecorps.pcsa.circle_of_trust.Trustees class with the latest update.
![screenshot from 2016-04-02 21 14 56](https://cloud.githubusercontent.com/assets/754909/14227311/39057986-f918-11e5-9dd0-7fe112fb1903.png)

**Comment by chamika** [comment]
Shall I fix this and send a quick PR

**Comment by sandarumk** [comment]
yes.

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PCSA-Android/pull/186
