### ISSUE TITLE
Adhering to the styles of the app

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#187]
The "SAVE" button in Add Trustees Activity doesn't change it's appearance when pressed, unlike all the other buttons in the app.
Similarly, "Voice Call" and "Send Message" options in the dialog boxes are missing change in its appearance on pressing them.

**Comment by sandarumk** [comment]
can you please add the screen shots too

**Comment by rohands** [comment]
![screenshot_2016-04-02-23-40-01](https://cloud.githubusercontent.com/assets/8949393/14228249/4429fd54-f92d-11e5-966c-fced292d8eb1.png)

This is how the change in UI has been implemented on pressing the buttons

![screenshot_2016-04-02-23-41-10](https://cloud.githubusercontent.com/assets/8949393/14228252/4fd4f38e-f92d-11e5-9d55-3ed610afe678.png)

![screenshot_2016-04-02-23-44-53](https://cloud.githubusercontent.com/assets/8949393/14228253/5576a012-f92d-11e5-9356-63a318219a91.png)

As we can see, no changes on pressing the buttons
PS: Had a hard time getting screenshots while pressing the buttons :P

**Comment by sandarumk** [comment]
Voice call and send message doesn't need the change. But for the "Save" you can add. Better to confirm it with @calistus

**Comment by rohands** [comment]
Sure, will wait for @calistus approval

**Comment by rohands** [comment]
@sandarumk Found another issue similar to the above mentioned. 
Lacking similarity in design of dialogs. 
![screenshot_2016-04-03-00-06-46 1](https://cloud.githubusercontent.com/assets/8949393/14228368/659c3d0a-f930-11e5-8b4e-18b2a58997dc.png)
<strong>Versus</strong>
![screenshot_2016-04-03-00-06-57 1](https://cloud.githubusercontent.com/assets/8949393/14228371/6f1d7b6e-f930-11e5-975b-0ad8b522641c.png)
Colors, dividers, text styles, none of these seem to match. 
Would look better if it was implemented like the second one

**Comment by sandarumk** [comment]
@calistus @Buddhiprabha Why is these two dialog boxes are different? Should they be alike or the current implementation is approved?

**Comment by Buddhiprabha** [comment]
I agree with the fact that "Select a request" should also agree to design uniformity. @calistus please confirm.

**Comment by Buddhiprabha** [comment]
But these are two different issues. @rohands your fist issue is similar to the issue at https://github.com/systers/PCSA-Android/issues/182

**Comment by rohands** [comment]
@Buddhiprabha yes, I took a look at the open issues before posting this. Looks like issue #182 talks about the Help Me button's ripple effect. (this is not generic in the app)
Here, I'm talking about the generic styles used in the app for a simple button ("SAVE" in Trustees).

**Comment by rohands** [comment]
@Buddhiprabha If need be so, I shall open another issue just for the "Select a request" dialog box.

**Comment by calistus** [comment]
You can move ahead with the changes:
i. Styling of the save button when pressed
ii. Change the look and feel of "select request" dialog box  to follow app look and feel

**Comment by rohands** [comment]
@sandarumk 
As identified by @Buddhiprabha, I shall consider them as two different issues and make PRs.

**Comment by sandarumk** [comment]
merged.
