### ISSUE TITLE
Lag in drawing layout for ContactPostStaff observed

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#189]
I'm using Samsung Galaxy S4. Not sure if this is happening on other devices. 
The issue is with the text "This is information for Uganda/Syria/Tunisia" in ContactPostStaff
Steps to reproduce - 
1. Go to Reporting Process
2. Go to Contact Staff to Report
3. Press the right arrow (You'll go to ContactOtherStaff activity)
4. Now press the left arrow (You'll come back to ContactPostStaff*)

When you're coming back to ContactPostStaff, notice the text in the end. The last part "Uganda/Syria/Tunisia loads with a bit of lag.

**Comment by yogeshbalan** [comment]
It is basically due to their ROM. It adds an additional lag while going through such transition. I would advice you to test the app in a stock ROM or other smartphones as well. It is working fine in my NEXUS 5x

**Comment by rohands** [comment]
Oh okay. Thank you @yogeshbalan. So, this can't be fixed right?

**Comment by yogeshbalan** [comment]
Yes. It is due to ROM. Although lag can occur also due to presence of a very high res image or res, which is clearly not an issue here

**Comment by rohands** [comment]
Oh okay. I'll wait for what the mentors have to say before closing the issue
