### ISSUE TITLE
Adhering to Java naming convensions

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#190]
As per the Java naming conversion, constants must be named in all capitals like - CONSTANT_ONE. In Trustee.java, however this convention has not been followed-
```java
    public static final String comrade1 = "comrade1Key";
    public static final String comrade2 = "comrade2Key";
    public static final String comrade3 = "comrade3Key";
    public static final String comrade4 = "comrade4Key";
    public static final String comrade5 = "comrade5Key";
    public static final String comrade6 = "comrade6Key";
```
I would like to fix this.

**Comment by calistus** [comment]
Good observation.
You can rename the constants and send a PR.  Make sure the name change is effected in all the places where those constants were used

**Comment by yatna** [comment]
PR sent #208

**Comment by sandarumk** [comment]
merged
