### ISSUE TITLE
Duplication of phone numbers not taken care of properly

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#193]
I was testing the <strong>Add Trustees</strong> functionality for all different test cases and I found a test case for which it failed to give me the desired output. 

1. When you try to retrieve a contact which has multiple phone numbers linked to it, Android provides you an option to select from one of them. 

For some reason, let's say I have a contact in my phone which was stored with two same phone numbers, one with the country code and the other without it. (I do)

![screenshot_2016-04-03-19-03-23](https://cloud.githubusercontent.com/assets/8949393/14232656/e0147158-f9ce-11e5-865d-ecf7c03f6b86.png)

If I pick the first number the first time and second number the next time, the previously implemented logic fails to check duplicacy in this case.

**Comment by AkankshaBodhankar** [comment]
This is a duplicate issue refer to #158

**Comment by AkankshaBodhankar** [comment]
@rohands The logic for the same will be implemented once validations are done so that we can implement this functionality better follow the discussion going on in the mentioned issue

**Comment by rohands** [comment]
Oh okay, sorry for not noticing this earlier @AkankshaBodhankar
