### ISSUE TITLE
Bug in Trustees

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#194]
Sometimes when I pick a contact using the "Contact Picker" in <strong>Add trustees</strong>, there are unnecessary whitespaces between the digits of the phone number because of which some of the functionality implemented/ being implemented will fail. 
Two of them I can think of are : 

1. The regex being built to validate phone numbers will fail due to presence of unnecessary whitespaces in between the digits. Well, you could always make the regex pattern match the spaces that could appear but this leads to more questions. Where does the space appear? If so, how many such spaces? It seems to be cumbersome to build a pattern like this. Logic will be complicated, simple fix - just trim the spaces.

2. The logic to check for duplication of numbers will fail

Here is a screenshot which shows how the spaces appear between the digits. 

![screenshot_2016-04-03-19-19-48](https://cloud.githubusercontent.com/assets/8949393/14232730/2fd27350-f9d1-11e5-8c96-0ebcb25e1c43.png)
  
Fix : Trim the number

**Comment by rohands** [comment]
@sandarumk Shall I make a quick PR on this?

**Comment by sandarumk** [comment]
This will be solved with #158 and #84 .
