### ISSUE TITLE
Stray character in strings.xml file

### ISSUE THREAD

**Issue by hkasera** [systers/PCSA-Android#202]
In the [`strings.xml` file at line number 50](https://github.com/systers/PCSA-Android/blob/develop/app/src/main/res/values/strings.xml#L50) I notice a stray character **C** preceding the string tags. 
<img width="1174" alt="screen shot 2016-04-06 at 1 44 55 pm" src="https://cloud.githubusercontent.com/assets/6101687/14310106/ce49fdea-fbfd-11e5-8670-e382ee66b1b3.png">

I believe it is unintentional and should be removed.

Thanks,
Harshita

**Comment by calistus** [comment]
Remove it and send a PR

**Comment by hkasera** [comment]
Sure thanks will do now :+1:
