### ISSUE TITLE
Trustees.java giving error on compilation

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#207]
![screenshot from 2016-04-07 01 32 49](https://cloud.githubusercontent.com/assets/8321130/14330998/e8e13ce6-fc60-11e5-9408-1ef227cab44f.png)

This occurs because new_comrade1, new_comrade2 ... new_comrade6 have not been defined as strings.
Also, noDuplicateNumber() does not exist , yet it has been called 
```java
okButton.setOnClickListener(new View.OnClickListener() {
           
	    @Override
            public void onClick(View v) {
                 
		boolean noDuplicateNumber = noDuplicateNumber();

                //To store previous values (numbers) of comrades
                List<String> old_comrade = new ArrayList<String>(NUMBER_OF_COMRADES);
```

**Comment by sandarumk** [comment]
I think it is beacuse of the new PR which has been merged. You can fix this and send a PR

**Comment by yatna** [comment]
@sandarumk Yes, the contributer added his own version of previous functions but forgot to remove duplicate older once.

**Comment by yatna** [comment]
PR sent #209
