### ISSUE TITLE
Undefined behaviour in Circle of Trust in the current build

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#211]
![screenshot_2016-04-08-02-46-15](https://cloud.githubusercontent.com/assets/8949393/14367262/970669a8-fd34-11e5-94c4-ffbfbd60fb5d.png)

<strong> Only 1 number registered </strong>

<strong> Shows message is sent to 6 comrades </strong>
![screenshot_2016-04-08-02-46-53](https://cloud.githubusercontent.com/assets/8949393/14367266/99969936-fd34-11e5-8006-a9eb0c33e1f3.png)

**Comment by rohands** [comment]
The app is currently sending message to phone numbers "1","2","3","4","5","6"

![screenshot_2016-04-08-19-42-09](https://cloud.githubusercontent.com/assets/8949393/14386378/173dbb2a-fdc2-11e5-9434-5b45fd1d91d2.png)

Reason (Bug) : 

<code>
private boolean loadPhoneNumbers() {
        sharedPreferences = this.getActivity().getSharedPreferences(Trustees.MY_PREFERENCES, Context.MODE_PRIVATE);
        try {

            phoneNumbers = new String[Trustees.NUMBER_OF_COMRADES];
            for(int i = 0; i < Trustees.NUMBER_OF_COMRADES; i++)
                <strong>phoneNumbers[i] = Trustees.COMRADE_KEY.get(i);</strong>

            return true;
        } catch (Exception e) {
            Log.e(TAG, "Unable to load comrades numbers from shared preferences", e);
        }

        return false;
    }
</code>

This function is expected to retrieve the comrades' phone numbers which have been locally stored in Shared Preferences. The highlighted code was written with the intention to achieve this but it fails. The array phoneNumbers[] which was expected to have the phone numbers has only texts "comrade1key","comrade2Key" .. "comrade6key". 
This line must be replaced by 
<code>
<strong>phoneNumbers[i] = sharedPreferences.getString(Trustees.COMRADE_KEY.get(i), "");</strong>
</code>

This will clear the bug,

**Comment by rohands** [comment]
<strong>Reason (Bug) :</strong>  

<code>
   private boolean loadPhoneNumbers() 
   {
        sharedPreferences = this.getActivity().getSharedPreferences(Trustees.MY_PREFERENCES, Context.MODE_PRIVATE);
        try 
        {
            phoneNumbers = new String[Trustees.NUMBER_OF_COMRADES];
            for(int i = 0; i < Trustees.NUMBER_OF_COMRADES; i++)
                <phoneNumbers[i] = Trustees.COMRADE_KEY.get(i);
            return true;
        } catch (Exception e) {
            Log.e(TAG, "Unable to load comrades numbers from shared preferences", e);
        }
        return false;
    }
</code>

This function is expected to retrieve the comrades' phone numbers which have been locally stored in Shared Preferences. The highlighted code was written with the intention to achieve this but it fails. The array phoneNumbers[] which was expected to have the phone numbers has only texts "comrade1key","comrade2Key" .. "comrade6key". 
This line must be replaced by 
<code>
phoneNumbers[i] = sharedPreferences.getString(Trustees.COMRADE_KEY.get(i), "");
</code>

This will clear the bug,

**Comment by sandarumk** [comment]
I think the two issues are fixed now after the revert. Please check.

**Comment by rohands** [comment]
@sandarumk This issue is also fixed after you reverted into an earlier commit. I'll close the issue
