### ISSUE TITLE
Serious bug in the logic used for checking duplicacy of phone numbers

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#214]
<pre>
<code>
    private boolean noDuplicatedNumber() {

        Set<String> comradeTexts = new HashSet<>();
        for (int i = 0; i < NUMBER_OF_COMRADES; i++)
            comradeTexts.add(comradeEditText.get(i).getText().toString());
        return comradeTexts.size() != NUMBER_OF_COMRADES;
    }
</code>
</pre>

As we can see, the developer has intended to check duplication by adding elements to a set and then checking if the size of the set is the same as the number of comrades. 
It returns true (which means no duplication) even though there is duplication. For example, let's say these are the comrade numbers

**Test case 1:**
Comrade 1 - 9986180939
Comrade 2 - 9986180939 (same as comrade 1)
Comrade 3-6 - Different numbers
(We expect that for this test case, we get false in return which means that there is a duplicate number)

So, on debugging -  
The size of the set is 5 since Comrade 1 and Comrade 2 are same. Which is not equal to _NUMBER_OF_COMRADES_ (6). Hence it returns true (which means there is no duplicate number)

**Test case 2:**
Comrade 1-6 - All different numbers (We expect that this function returns true, which means there is no duplicate number)

If we trace the code,
The size of set here is 6, since all the numbers are different. Hence it returns false for the expression "6 != 6"
Which means that there is a duplicate number. Logic fails.

**Fix in the logic :** 
- Count the number of comrades which are registered and store it 

- Add these numbers to set

- Now check the size of set against the value stored in Step 1

**Comment by AkankshaBodhankar** [comment]
@rohands @sandarumk The logic which i implemented for duplicacy is the same what rohan is mentioning. The bugs in the functionality are arising due to the new PR that has been merged. A lot of changes have been done to the code at Trustees.java 

The initial logic which i implemented has been totally changed by the new developer
![screenshot 551](https://cloud.githubusercontent.com/assets/14356938/14408711/88eebc18-ff1d-11e5-83e5-f6cb4e17291c.png)

**Comment by AkankshaBodhankar** [comment]
The new bug #215 has also arised due to the same PR.

**Comment by AkankshaBodhankar** [comment]
@rohands @sandarumk I suggest that we change the code at Trustees.java to the old one (which was written before merging the new PR). All the new bugs arising in Trustees.ajava will be automatically resolved.

**Comment by rohands** [comment]
Yes, I think so too!

**Comment by sandarumk** [comment]
Reverted. Check whether this works now.

**Comment by rohands** [comment]
@sandarumk Duplication works fine.
