### ISSUE TITLE
Registering phone numbers using contact picker fails in the current build

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#215]
The app toasts the message  "Duplicate number" if we try to pick a contact. 
![screenshot_2016-04-08-20-40-13]
(https://cloud.githubusercontent.com/assets/8949393/14388148/68f22cfa-fdca-11e5-82bd-cdf701385c42.png)

Needs to be fixed.

**Comment by sandarumk** [comment]
Fixed by reverting #179
