### ISSUE TITLE
Abrupt closing of Trustees on pressing back button

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#217]
Suppose, the user has entered some comrade numbers while registering the comrades in Trustees, now by mistake, if he/she presses back button, she'll have to redo the whole process again. A better implementation would be alert the user to save the changes. 
Maybe we can create an alert dialog to inform the user to **save** or **cancel**

**Comment by sandarumk** [comment]
Duplicated with #103 . Please go through the issue list (both open and closed) before you make a new one.
