### ISSUE TITLE
Change the theme of multiple contact number dialog box

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#219]
In add comrades' numbers, the user can select a contact to add the phone number. If the selected contact has multiple phone numbers, a dialog box will be shown like below screenshot.
![screenshot_2016-04-11-21-34-23](https://cloud.githubusercontent.com/assets/754909/14433876/c407f45c-002d-11e6-858a-c0f6c48f921f.png)

For the dialog boxes, there is a standard theme which is used in "contact staff". Same theme can be used here.

**Comment by sandarumk** [comment]
Yes. you can go ahead and submit a PR. Please post a screen shot of the new dialog box in the comments before you submit the PR/

**Comment by chamika** [comment]
The suggested implementation would be like this
![screenshot_2016-04-12-23-21-46](https://cloud.githubusercontent.com/assets/754909/14470149/9222e5ae-0105-11e6-8310-53436e598c12.png)

**Comment by sandarumk** [comment]
Remove the image icon. Just the number is enough. Can you add another screenshot removing that.

**Comment by chamika** [comment]
Remove image icon 
![screenshot_2016-04-12-23-57-31](https://cloud.githubusercontent.com/assets/754909/14471077/5dd802a2-010a-11e6-9c9b-13669d1dc1ec.png)

**Comment by sandarumk** [comment]
This looks fine.

**Comment by sandarumk** [comment]
Merged
