### ISSUE TITLE
Duplicate Application Test classes

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#220]
There are two test classes with the same name and the source
1. [https://github.com/systers/PCSA-Android/blob/develop/app/src/androidTest/java/com/pcsa/ApplicationTest.java](url)
2. [https://github.com/systers/PCSA-Android/blob/develop/app/src/androidTest/java/com/peacecorps/pcsa/ApplicationTest.java](url)

Considering the application package 1st test class can be removed.

**Comment by sandarumk** [comment]
The first one should be removed. You can go ahead and make a PR for this.

**Comment by Buddhiprabha** [comment]
Fixed
