### ISSUE TITLE
strings refactor in strings.xml and information.xml

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#223]
strings.xml supposed to include only the short texts which appear in the application components. information.xml is used as the content source of the application where long texts are stored. 

The following two strings should be moved from strings.xml to information.xml
`reporting_desc_standard`
`reporting_desc_restricted`

**Comment by Buddhiprabha** [comment]
@chamika Please provide a reference which includes the best practice regarding this. You can proceed afterwards.

**Comment by chamika** [comment]
There is no standard or best practice for storing content and UI component texts in xml resources. The app developers have followed this practice and it seems a good idea to maintain two string resource files for app related content and UI component texts for maintaining clean strings.xml file. 

Depending on this categorization, mentioned two string should be placed in the information.xml file.

**Comment by Buddhiprabha** [comment]
@chamika thank you for the suggestion. Please proceed.

**Comment by AkankshaBodhankar** [comment]
This issue is resolved I guess this is good to be closed

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PCSA-Android/pull/237
