### ISSUE TITLE
Organised distribution of drawable and res item

### ISSUE THREAD

**Issue by yogeshbalan** [systers/PCSA-Android#225]
According to **Google Guidelines** the current app res folder should be arranged in the following manner  :- 

MyProject/ 
  -   res/ -> drawable/  **Bitmap files (.png, .9.png, .jpg, .gif) or XML files that are compiled into the following drawable resource subtypes:**

                         -  Bitmap files
                         -  Nine-Patches (re-sizable bitmaps)
                         -  State lists
                         -  Shapes
                         -  Animation drawables
                         -  Other drawables 

- res/ -> mipmap/ **Drawable files for different launcher icon densities. For more information on managing launcher icons with mipmap/**

Currently in app some of the images are kept in **/mipmap** which is not according to the guidline as 
proposed by google. [Link1](http://developer.android.com/guide/topics/resources/providing-resources.html) [Link2](http://developer.android.com/tools/projects/index.html#mipmap)

Solution : Change structure of res directory according to the guidlines

**Comment by yogeshbalan** [comment]
also images of non-standard dimensions should be added into
 /res/drawable-nodpi
and
/res/drawable-mdpi - resources for medium pixel density
/res/drawable-hdpi - resources for high pixel density
/res/drawable-port - resources just for portrait mode and so on.

**Comment by sandarumk** [comment]
We might not need /res/drawable-port since the current context has no difference in landscape and portrait modes. But you can go ahead with the refactoring.

**Comment by yogeshbalan** [comment]
PR #227 sent

**Comment by sandarumk** [comment]
Merged.
