### ISSUE TITLE
App doesn't alert the user when message is being sent to a wrong phone number 

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#229]
In #161, I was assigned an issue by @calistus which was overlooked maybe because I gave my thoughts further on how to improve the use-case of the issue.  
However, I hadn't implemented the basic functionality yet (to actually check whether the sms was sent)
But the issue was tagged suggestion and closed. Shall I fix the issue which I was assigned and that is to check if the SMS was actually sent/delivered to the comrade?

**Comment by sandarumk** [comment]
Do not make duplicate issues. We can always reopen an issue if it needed to be addressed again. Please use that comment thread for further discussion so that if we want to re open that issue we will.
