### ISSUE TITLE
Circle of Trust Activity UI can be more informative

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#23]
I'm not sure if this is required but it would be great to have something like 

![comrades](https://cloud.githubusercontent.com/assets/8949393/12208960/1ad2306a-b676-11e5-986a-7695554889e0.png)

By doing this, it would give a clear picture about the registered comrades. Also, on editing the comrades, the registered numbers are displayed right there. 
Also, on editing the comrades, the user needs to click the back button to perform any further changes. 

I've already implemented the workaround for the above mentioned issues. I'll submit a PR as soon as this is approved as a valid issue.

**Comment by calistus** [comment]
Yes it is a nice idea to display the comrades number on the circle of trust activity, but icons should take the shape of a circle . Attached is a raw mathematical concept which you can use to make it take the shape of a circle. You can use Table layout to achieve this.
When you are done, then you can send a PR

![img_20160110_012359](https://cloud.githubusercontent.com/assets/7851155/12219208/44d56e86-b739-11e5-8be2-125ea7992ef0.JPG)

**Comment by rohands** [comment]
Thank you @calistus.
I'm working on this.

**Comment by sandarumk** [comment]
There is a current issue open for circle of trust displaying off center.  I think if you want to work on this it is better to wait until that PR is reviewed and merged. It will help you to do this without any conflicts on the code.

**Comment by rohands** [comment]
I made a pull request. 
#27
Unnecessary files seem to be showing up

**Comment by rosariorobinson** [comment]
Thanks for this initiative, but let me give you some background. 

[1] This design was thoughtfully and carefully addressed by UI/UX experts at General Assembly for Peace Corps. This is not something that was just designed, but the color scheme and how users would need to access these features and buttons on an instant in at times dire situations. So while we can perhaps come up with better UI idea, this design really targets the users. 

[2] The point behind "**Circle **of Trust" is a cognitive relationship which is part of UX. 

[3] Systers picked up this project to apply the development/code behind the initial design. 

So while I appreciate the creative extension of this issue, the design will not change and Peace Corps has accepted this design. Now, with that said, it doesn't mean there won't be any design changes down the road, but for now, we are not changing the design.

**Comment by rohands** [comment]
Thank you for reviewing @rosariorobinson.
My thoughts on this - 
Well, you might have overlooked the comments in the issue. The issue had initially been opened by me with a clear intent of changing the design. However if you see what @calistus has suggested, it looks like the design is still the same. Just that, it now has a better implementation. Instead of trying to create a circle with a bunch of linear layouts, using a table layout makes it mathematically correct, if what is intended is to to have a circle.
The <i>Circle</i> which we are trying to create in <strong>Circle of Trust</strong> looks better with a TableLayout and that could probably be something that @calistus intended too.

**Comment by rosariorobinson** [comment]
I understand your point, but again, this was thoughtfully designed. 

This a safety app and there is some design aspect that are important. 

Circles are easier on the eyes. In the UI research space, circles protect, restrict and they endure. These characteristics are important to the users of this app. S

The technical aspects of the design may be mathematically correct, but for this app (and most mobile apps I hope) are really considering the users. Looking better and sensible Implementation is one thing, but understanding the usability of this app is more important, and particularly understanding WHO may potentially use the app.

I appreciate your persistence and passion about the design.

**Comment by rosariorobinson** [comment]
@rohands based on your comments, you state the 'design' has not changed, is this correct? what is this PR trying to address?

**Comment by rohands** [comment]
Before.
![aj21pc4ogoy0jn10-9zoiv0plosq0lyrnd59vlme2vze](https://cloud.githubusercontent.com/assets/8949393/12826193/ded62f96-cb9f-11e5-8275-b6f40019919b.jpg)

After.
![19aac6d8-b7da-11e5-978e-411f98160649](https://cloud.githubusercontent.com/assets/8949393/12826196/e4a21188-cb9f-11e5-8a28-6bf5437e50b5.jpg)

Points to note : 
1) Circle is better implemented using a table-layout and like I mentioned a while ago, it's better implemented. 
2) Numbers are displayed right there. 
If you feel that there's not much difference in the way the circle is outlined, I guess this issue should be closed. 
PS : There are conflicts in font style, will rectify once the PR is accepted.
Thanks again @rosariorobinson

**Comment by rohands** [comment]
Advantages - 
1) Can verify if the ph nos entered are right
2) On clicking the OK button in edit comrades, a toast appears like before, and the user is navigated to the circle of trust page unlike earlier where it stays in the same activity (better UX)

**Comment by rosariorobinson** [comment]
We should not display their name or number on the circle of trust. 

I can keep this open to submit to Peace Corps for review as far as the spacing.

**Comment by rohands** [comment]
@rosariorobinson  
I was looking at the mock design put up by the team. It says the Comrade Names also need to be displayed. I guess, this PR solves that problem too. (Numbers are not required, I'll edit them )

**Comment by sandarumk** [comment]
The UI of this screen should not be changed at this moment. If we are going to change it after consulting Peace corps, we will let you know.  As suggested by @rosariorobinson we can keep this open until then.

**Comment by sandarumk** [comment]
Meanwhile let me clarify you the rationale behind the design decision. This app is designed to use at extreme circumstances. So when a person clicks the circle of trust option that means he/she wants to send a "Shout for Help" for his/her comrades. At this moment he/she will only have to click the middle "help me" button. So there is actually no use in adding names and numbers of the comrades because it will only make the screen filled with data and may lead to confuse the user.

**Comment by rohands** [comment]
![download](https://cloud.githubusercontent.com/assets/8949393/12925506/94ac2504-cf84-11e5-9a85-194bc906b3c6.png)
@sandarumk , does this mean there's a need to change the mockup design ?

**Comment by sandarumk** [comment]
If you are talking about the "Help Me" button menu, no the design shouldn't be changed. It is the required functionality. But if you are talking about the names of comrades, yes a small change in the design is needed. We will update the document.

**Comment by rohands** [comment]
@sandarumk  Thank you for the review. I clearly understand the rationale behind the design decision now. 
Also, I was talking about the comrade names.

**Comment by rohands** [comment]
@sandarumk 
This PR had already solved the problem of reporting back to Circle Of Trusts on Clicking OK. Maybe you should consider this since I had raised the issue earlier? Or how does it work?

**Comment by sandarumk** [comment]
First of all I have to say sorry because it did not occurred to me that you have already mentioned about this issue in one of the comments in this thread when I approved the other contributors issue. So avoid any conflicts please report the issues separately. It will be easier for us to review and other willing contributors to find a new one rather than replicating an old issue. Since your issue is on Circle of trust UI, not the add comrades page, it will be easy to miss.
Your PR is rejected because it had the unnecessary UI change. Having one correct thing in the middle of something wrong does not make the wrong thing 100% correct. So next time add your issues and suggestions separately. (I am adding this fact to the README as well to avoid future confusions).

**Comment by rohands** [comment]
@sandarumk 
Noted.
