### ISSUE TITLE
Slide 3 in AppIntro needs updation

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#232]
![screenshot_2016-04-13-02-28-16](https://cloud.githubusercontent.com/assets/8949393/14475453/a9b636ca-011f-11e6-8e5e-42cfa5b5e0e9.png)

The UI for this dialog box has changed. Need to replace the current image with that of the new one.

**Comment by Buddhiprabha** [comment]
You can proceed with this

**Comment by sethbrudee** [comment]
I can

**Comment by sandarumk** [comment]
Merged.
