### ISSUE TITLE
Allow voice interactions

### ISSUE THREAD

**Issue by sandarumk** [systers/PCSA-Android#245]
Use Google voice interaction API to allow voice interaction. This will let you open the app using a voice command, go to circle of trust and use help me features while having a conversation with the mobile on your choices.
Inspired by: https://www.youtube.com/watch?v=OW1A4XFRuyc

**Comment by ashu-dadhich** [comment]
@sandarumk this sounds like a great enhancement to the app. If you don't mind may I ask why was it not implemented?
