### ISSUE TITLE
Add navigation drawer as shown in mockup

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#247]
As mentioned in #49, navigation drawer has to be included.

**Comment by rohands** [comment]
Working on this.

**Comment by sandarumk** [comment]
Since it is already covered in #49, do not create new issues. This is for the future development tasks as well. Only open an issue if it not covered in any of the issues previously reported.

**Comment by rohands** [comment]
@sandarumk Noted.

**Comment by AkankshaBodhankar** [comment]
@rohands I implemented the navigation drawer in my project PCSA webapp something like this thought it might help you (only peace corp logo has to be added yet  in the menu)

![slide-menu](https://cloud.githubusercontent.com/assets/14356938/15706905/9b087564-2813-11e6-833b-06245c7ae31b.jpg)
