### ISSUE TITLE
UX improvement

### ISSUE THREAD

**Issue by calistus** [systers/PCSA-Android#259]
@rohands 

Your GSoC journey so far has been good.  
I went through PCSA User Experience(UX) so far, and here is my review.

1.	The "S" on the peace corp icon on the navigation drawer was cut off a little bit. Apply some padding there.
2.	The Navigation drawer should span the height of the screen as prescribed by Android design principle; just the way it was represented on the mockup.
3.	The quality of icons and navigation drawer is poor. You can get standard design icons at: design.google.com/icons
4.	I can see an arrow icon overlapping with text on the navigation drawer. Please resolve that. If the list item does not drop down, then remove the icon(s)
5.	Whenever a user moves to a new activity, the activity name should be displayed on the Toolbar not as a Texview below the Toolbar. The essence of the tool bar is to tell the user where he is on the app. So all the bold titles on the activities should be moved to the Toolbar
6.	I have also had an experience while navigation and come back to the home activity, I only see a white(blank) background. Please find out where this is coming from and resolve it.

Below are some screenshot demo.

Let me know if you have any questions

![navigation drawer](https://cloud.githubusercontent.com/assets/7851155/16798720/602b77e6-48e5-11e6-86c2-d072023f0400.png)
![activity](https://cloud.githubusercontent.com/assets/7851155/16798738/6cac2c04-48e5-11e6-95f7-9d3ffd29bc18.png)

**Comment by rohands** [comment]
**activity_main** had a static fragment defined before. This has been changed to include a FrameLayout to accomodate for adding/replacing fragments dynamically. 
Having said this, except for the MainActivity everything else is now a fragment. And what is happening basically is mere swapping in and out of fragments. Therefore, the toolbar will always have **PCSA** as its content. 
    As discussed earlier in the mailing list, if we have to keep Safety Tools, Get Help Now, Support Services as separate activities then the code for navigation drawer will have to be included for all the layouts corresponding to these activities. To avoid such a great deal of redundancy, I chose to go with the all-fragment approach.  Would you have any idea on how I could resolve the issue?
    The white screen which appeared was identified and resolved. If you have the latest build, it will not appear. This was happening because of the addition of all fragments which were being instantiated to back stack. 
Everything else has been noted, I'll make the necessary changes. Thank you for reviewing.

**Comment by rohands** [comment]
@calistus 
I have fixed everything else apart from the toolbar issue. Waiting for your suggestion on how I could improve the current architectural state of the project

**Comment by calistus** [comment]
- Make the Toolbar a global object

- Dynamically change the Toolbar title whenever a new fragment is called. You can do this using 
`getSupportActionBar().setTitle("The Title");
`

 change the toolbar title when a new fragment is called using

**Comment by rohands** [comment]
Oh yes, thank you. That would be the way to go! I'll make a PR soon

**Comment by calistus** [comment]
Nice
