### ISSUE TITLE
Implement Reporting Steps as in Mockup

### ISSUE THREAD

**Issue by chhavip** [systers/PCSA-Android#26]
@sandarumk I went through the mockup provided and would like to implement the reporting steps page in the way described. Should I start working on that?

**Comment by rosariorobinson** [comment]
You can if you'd like. We're trying to get this to MVP.

**Comment by chhavip** [comment]
@rosariorobinson on it

**Comment by sandarumk** [comment]
Mockup changed with the vertical design we already had. Closing the issue.
