### ISSUE TITLE
Reporting Types Activity UI can be restructured to include Tabs.

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#28]
Provides a seamless UI Experience. 

Could so something like this. 
![124f7dbe-1296-470a-8208-c9f7085a0ead](https://cloud.githubusercontent.com/assets/8949393/12222205/46206aaa-b7db-11e5-8bf9-b7bcbb06b145.jpg)

**Comment by rosariorobinson** [comment]
Again, please note my comments from issue #23
