### ISSUE TITLE
Implementing Get Help Now as in mockup.pdf

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#29]
I wanted to implement get help now as shown in mockup.pdf, can I continue?

**Comment by rosariorobinson** [comment]
Where is the mockup.pdf? Is this consistent with already design mockup that team implemented?

**Comment by rohands** [comment]
Apparently yes. 
This could help -
<a href="https://github.com/systers/PCSA-Android/blob/develop/docs/design/mockup.pdf">Link to mockup.pdf</a>

**Comment by rohands** [comment]
@rosariorobinson 
This is the document which has the design mockup that the team has implemented.

**Comment by rohands** [comment]
@rosariorobinson  @sandarumk 
I request one of you to let me proceed with this.

**Comment by rosariorobinson** [comment]
Yes, continue. If @sandarumk or @calistus don't have any objections, proceed.

**Comment by rohands** [comment]
I will start off  implementing as shown in mockup

**Comment by rohands** [comment]
Thank you @rosariorobinson

**Comment by sandarumk** [comment]
I am okay with it. @calistus  do you have any suggestions?

**Comment by rohands** [comment]
Thank you @sandarumk. Maybe you could also review #27 once?

**Comment by calistus** [comment]
@Rohan you can continue but make sure that the UI is responsive on both
small screen and larger screen devices

**Comment by rohands** [comment]
@calistus Sure, I'll keep that in mind while I'm on it.

**Comment by rohands** [comment]
In the current implementation, "Get Help Now" is located in "Contact Staff to Report" which is in "Reporting Process"

There's also "Get Help Now" in the main activity which doesn't have any functionality yet. 
So, is it planned to move it from Reporting Process to the main window? 
Where should I make changes to the code?

**Comment by sandarumk** [comment]
@rohands Sorry for the late reply. When you suggest this issue, what was your idea? What did you meant by implementing the 'Get Help Now' as in the mockup? Did you meant the already implemented one in the reporting process?

**Comment by rohands** [comment]
"Get Help Now" isn't implemented yet. The mockup shows layouts very similar
to Reporting Process with some minute differences
So I wasn't sure what to do.
Can you tell me how to go about this?
Should I create new layouts ? Or just make changes to the reporting process
and inflate those layouts for "Get Help Now"?

**Comment by rohands** [comment]
@sandarumk, it would be better to have ContactPostStaff and
ContactOtherStaff as fragments, by doing which we can have support for
different screen sizes as @calistus suggested.

Also, if you'd not want to have "Get Help Now" implemented yet, I'd like to
change this issue to just change the dialog box UI which appears on
clicking any of the buttons in ContactPostStaffActivity and
ContactOtherStaffActivity

**Comment by sandarumk** [comment]
If you check the mockup the "get help now" from the initial and the reporting process leads to the same pages (7 and 8 in the mockup). Sorry fro not noticing that earlier. Since the ContactPostStaff and ContactOtherStaff is already implemented keep them as it is. You are welcome to change the dialog box. Please attach a screenshot on how you are going to change the dialog box.

**Comment by rohands** [comment]
![pcmo](https://cloud.githubusercontent.com/assets/8949393/13397058/1fb1357e-df1e-11e5-8945-a2a0b766eb45.jpg)
The Dialog box would look like this in accordance with the mockup. 
Shall I proceed with the PR?

**Comment by Buddhiprabha** [comment]
@rohands you can continue with changing the dialog box as suggested.
