### ISSUE TITLE
Redundant Toast message display code in multiple places

### ISSUE THREAD

**Issue by hkasera** [systers/PCSA-Android#30]
Over in the [`MainActivityFragment.java`](https://github.com/systers/PCSA-Android/blob/develop/app/src/main/java/com/peacecorps/pcsa/MainActivityFragment.java#L46) as well as in the [`HomeScreen.java`](https://github.com/systers/PCSA-Android/blob/develop/app/src/main/java/com/peacecorps/pcsa/reporting/HomeScreen.java#L60) I noticed that the same line of code is written multiple times. I would like to fix this. Is this a welcome contribution right now?

**Comment by sandarumk** [comment]
The redundant toast messages are there until the functionalities are implemented in the next sprint. So there is no critical need for a fix since they are temporary.

**Comment by hkasera** [comment]
Sure alright!
