### ISSUE TITLE
Improper back navigation in SafetyPlanActivity

### ISSUE THREAD

**Issue by pandilladivya** [systers/PCSA-Android#306]
In **SafetyPlanActivity** when *Back Button* is clicked, It always goes to home page.

![c1](https://cloud.githubusercontent.com/assets/16818129/20634505/da203530-b377-11e6-899c-cd5d481487a7.PNG)

![c2](https://cloud.githubusercontent.com/assets/16818129/20634507/e013d82a-b377-11e6-9081-d55cdf37d270.PNG)

**Comment by pandilladivya** [comment]
@sandarumk 
Can I work on this Issue?

**Comment by sandarumk** [comment]
@pandilladivya before you go ahead with this please fix the issue with #298 .

**Comment by sandarumk** [comment]
fixed with #308
