### ISSUE TITLE
Moving constant values to a static class

### ISSUE THREAD

**Issue by hkasera** [systers/PCSA-Android#31]
Over in the [`CircleOfTrustFragment.java`](https://github.com/systers/PCSA-Android/blob/develop/app/src/main/java/com/peacecorps/pcsa/circle_of_trust/CircleOfTrustFragment.java#L92), I noticed that we have used harcoded strings for switch case. 

I suggest we should put these constant values in a static class. This way we can reuse the same information later as well.

Let me know if this is a welcome change. If yes, I will send a pull request for the same.

Thanks,
Harshita

**Comment by sandarumk** [comment]
Hi Harshita,
Yes. you can go ahead.

**Comment by hkasera** [comment]
This is merged (https://github.com/systers/PCSA-Android/pull/32)
