### ISSUE TITLE
Jerky Scrolling at various places

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#310]
The scrolling is not smooth in following - 

1. Tactics of Sexual Predators
2. Services after a Sexual Assault
3. PC commitment to Sexual Assault
4. What to do after an Assault > Peace corps ongoing support , Immediate response
5. Was it Sexual Assault > Sexual Assault
6. Impact of Sexual Assault
7. Peace corps policies

I have solved the problem. Should I send the PR. Thanks

**Comment by sandarumk** [comment]
@codingblazer Can you describe here what was the problem and how did you fix it?

**Comment by codingblazer** [comment]
@sandarumk Problem was that earlier , only .setMovementMethod(new ScrollingMovementMethod()); method was applied on textview to get scrolling behavior but this method does not provide kinetic scrolling (in one free scroll by user only a fixed distance is moved whether a stroke was long or small unlike standard behavior of scroll in any other app)
 To solve this , I have surrounded textview by ScrollView in XML file which offers kinetic scrolling. Also to retain the UI , I have moved some attributes of textview like margin , background etc to Scrollview.
Should I send PR if it seems fine. Thanks.

**Comment by rohands** [comment]
That's a good fix. Please implement these changes in all the textviews which do not have kinetic scrolling.

**Comment by codingblazer** [comment]
@sandarumk @rohands PR sent #312

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/FirstAide-Android/pull/312
