### ISSUE TITLE
Add predefined SMS body.

### ISSUE THREAD

**Issue by m-murad** [systers/PCSA-Android#311]
In "Get Help Now" menu there are options to contact PCMO, SSM and SARL via call and SMS.

I suggest that we add some predefined text in the SMS message body if the user choses to contact via SMS. The SMS body can contain simple text like

"Hello PCMO
This is <UserName>
Need help."

or it can also contain some text and the location of the volunteer.

@sandarumk  Should I send a PR.
Also if you have any thing in mind for the SMS, please tell.

**Comment by sandarumk** [comment]
Please keep the SMS for Get Help Now as it is. We currently do not need to change this.
