### ISSUE TITLE
Navigation Bar Needs Double Touch at some positions 

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#313]
Navigation Bar has following problems -
1. Currently , in navigation bar user has to touch twice on if position is any of 0,1,6,7 in navigation bar in order to open corresponding item.
2. If some group is already expanded in navigation bar and other group is expanded , then last expanded group should collapse (which is standard behavior) but it doesn't happen.

**Comment by codingblazer** [comment]
The problem can be solved as follows - 

1. Currently ,action on 0,1,6,7 positions is handled in the setOnGroupExpandListener of Expandable listview of navigation bar but it should be handled in setOnGroupClickListener instead.

2. This problem can be handled by adding a check condition in setOnGroupExpandListener which will close previously expanded group if any.

@sandarumk @rohands Should I send a PR ?

**Comment by rohands** [comment]
Yeah, this seems to be a legit issue. Please go ahead

**Comment by codingblazer** [comment]
@rohands Yeah sure.

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/FirstAide-Android/pull/318
