### ISSUE TITLE
App crashes after clicking back button followed by orientation change

### ISSUE THREAD

**Issue by jacqueline8711** [systers/PCSA-Android#316]
For example start at this screen (most other screens work too - not settings): 
![screenshot_20161203-111709](https://cloud.githubusercontent.com/assets/16260112/20858778/20a08070-b94d-11e6-9ff0-52d1ff55e212.png)
and then go to any other menu item (e.g. Circle of Trust), then click the back button (⊲) at the bottom of the phone and then change the orientation of the phone. 
This leads to a NullPointerException in MainActivity while trying to swap in a fragment that is null. Bug can be resolved by simply surrounding the swapFragmentIn() method call in line 75 of MainActivity with an if(unknownFragment != null) which is mentioned in the comment above it but was not implemented.

**Comment by sandarumk** [comment]
@jacqueline8711 Good work. Would you like to fox the issue as well? You can claim the task to "Claim and fix an issue" and comment here if you are willing to fix this.

**Comment by jacqueline8711** [comment]
Thank you @sandarumk for the information that this task exists. I have claimed the task and will now fix this bug.

**Comment by sandarumk** [comment]
Sure. Please join us in the slack channel as well. You can find the slack inviter in the organization page. If not let me know I will paste it in the task or here.

**Comment by sandarumk** [comment]
Resolved and merged
