### ISSUE TITLE
Dialog covers status bar

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#320]
@sandarumk @rohands 

Dialog covers the status bar in following (in Landscape mode) -

<img src="https://cloud.githubusercontent.com/assets/13872065/20860875/7a882a9c-b9a8-11e6-921c-eb198ce07e7e.jpeg" width="300" height="">
<img src="https://cloud.githubusercontent.com/assets/13872065/20860878/7f10ed10-b9a8-11e6-9fff-34f75b02c0e4.jpeg" width="300" height="">
<img src="https://cloud.githubusercontent.com/assets/13872065/20860880/8635e5b4-b9a8-11e6-9421-cdb5a5bc2d26.jpeg" width="300" height="">
<img src="https://cloud.githubusercontent.com/assets/13872065/20860882/86928d50-b9a8-11e6-8977-b1e488949306.jpeg" width="300" height="">
<img src="https://cloud.githubusercontent.com/assets/13872065/20860883/86937526-b9a8-11e6-9e0a-0c494ca4b22f.jpeg" width="300" height="">
<img src="https://cloud.githubusercontent.com/assets/13872065/20860931/a18bfbd6-b9a9-11e6-9267-b2c308e77f80.jpeg" width="300" height="">

**Comment by rohands** [comment]
@codingblazer 
Most of the issues generally fall into the category of not maintaining consistency with UI in landscape mode. 
Could you group all of them and leave a note here so that I could give you further instructions?

**Comment by codingblazer** [comment]
Yeah sure @rohands

**Comment by sandarumk** [comment]
#125 Is the original issue. You can directly comment there the rest of the UI inconsistencies in landscape mode. Then we can reopen that and fix. That issue is there to prevent people from opening multiple issues on multiple screens. What you have done is actually good because you have identified a sub section of the issue.

**Comment by codingblazer** [comment]
@rohands @sandarumk 
Please take a look at #125. I have listed all the landscape UI problems. Thanks.

**Comment by sandarumk** [comment]
@codingblazer  I am closing the issue since it is duplication of #125. We can continue the discussion on there
