### ISSUE TITLE
Widget for sending messages in Trustees Activity during emergencies

### ISSUE THREAD

**Issue by pandilladivya** [systers/PCSA-Android#323]
In case of emergency it's difficult for users to navigate to the Trustees screen and send messages to needed contacts.

So instead, we can have a widget implementing that same functionality of sending messages to the trusted contacts when there's an emergency

I'll start working on this issue as per its approval! :)
Thank you..

**Comment by sandarumk** [comment]
@pandilladivya When you report an issue, specially when it is a suggestion like this please see the closed issues as well. Because this has also been reported before and kept as a suggestion we are hoping to discuss. Also for the same functionality similar suggestions like #295 also put forward.

**Comment by sandarumk** [comment]
duplicated with #55

**Comment by pandilladivya** [comment]
@sandarumk 

Apologies for not viewing the closed issues properly.
Will take care of it from next time onwards :)
