### ISSUE TITLE
UI Enhancement for username validation in SignUpActivity

### ISSUE THREAD

**Issue by pandilladivya** [systers/PCSA-Android#325]
Instead of having a toast message (which stays for few seconds) for validation of Username, we can have an error message which is commonly used in any other android app for validating purposes.

Here are the screenshots of what can be done..

![login](https://cloud.githubusercontent.com/assets/16818129/21075621/7f912c34-bf3c-11e6-8d4c-214ae89998de.PNG)

![login2](https://cloud.githubusercontent.com/assets/16818129/21075617/7bdc7e04-bf3c-11e6-807d-1315a27196b5.PNG)

@sandarumk 
Kindly review and please let me know if it is a valid issue.
Thank you :)

**Comment by pandilladivya** [comment]
@sandarumk 
Should I send a PR for this?

**Comment by sandarumk** [comment]
We will keep this as a suggestion and discuss. Thank you for suggesting. We will let you know and reopen the issue.

**Comment by pandilladivya** [comment]
@sandarumk 
Thanks for the review! :)
