### ISSUE TITLE
Name remains blank in user setting.

### ISSUE THREAD

**Issue by saketkumar** [systers/PCSA-Android#327]
If we edit the name in user setting and set to blank , it goes blank and saves.

![sy1](https://cloud.githubusercontent.com/assets/21558765/21081128/61c8e958-bfe6-11e6-8588-2b54b7df3eca.jpeg)

Here name saved is now blank.

![sy2](https://cloud.githubusercontent.com/assets/21558765/21081129/6966b3f2-bfe6-11e6-948c-c5947abc1547.jpeg)

We can add an alert whenever the name editText is empty so that user cannot save a blank name.

@sandarumk Can i work on this?

**Comment by sandarumk** [comment]
Issue is duplicated with #297 . Please go through an updated version and check whether the issue still exists.

**Comment by sandarumk** [comment]
@saketkumar95 Any updates? Or shall I close the issue?

**Comment by saketkumar** [comment]
Yes this is solved now. Thanks for informing. Closing this.

**Comment by sandarumk** [comment]
Please make sure you always has the latest code when reporting issues.
