### ISSUE TITLE
Wrong email address in Office of Victim Advocacy 

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#329]
**Summary:** 

The email address given for **office of victim advocacy** in **Get Help now** fragment is wrong

**Steps to reproduce:** 

Change it in strings.xml

**Expected behavior:** 

email:_victimadvocate@peacecorps.gov_

**Observed behavior:** 

e-mail:_victimadvocate@peacecorps.-gov_
**Device and Android version:** 

Era X1 (Android Marshmallow) 

**Screenshots:** 

![image](https://cloud.githubusercontent.com/assets/15179401/21148454/4dbef0e4-c17e-11e6-80d9-ad01d960350d.png)

**Comment by ashu-dadhich** [comment]
the same goes for **Office of Inspector general**

**Comment by sandarumk** [comment]
This is a little bit unclear to me. Can you elaborate on why you change the email address in the first place (In steps to reproduce)?

**Comment by ashu-dadhich** [comment]
I googled it and it turns out their is no '-' after 'peacecorps.'

and thanks for correcting me about 'steps to reproduce'

**Comment by sandarumk** [comment]
So removing the steps to reproduce aside, the real issue is the minus in the e-mail address. Am I correct?

**Comment by ashu-dadhich** [comment]
:smile: yes

**Comment by ashu-dadhich** [comment]
should have kept it simple sorry about that

**Comment by sandarumk** [comment]
https://github.com/systers/FirstAide-Android/blob/develop/app/src/main/res/values/information.xml#L92
The e-mail address is in the information.xml. Not in the string.xml. Since the email address is correct in the xml and some screens it should be a text wrapping problem. Are you hoping to fix this?

**Comment by ashu-dadhich** [comment]
Yes I am should i start working?
Thank you

**Comment by sandarumk** [comment]
Before you start working can you explain how you are going to fix this?

**Comment by ashu-dadhich** [comment]
I haven't gone through the code yet can I tell you in the morning.

**Comment by sandarumk** [comment]
Sure.

**Comment by ashu-dadhich** [comment]
Thanks you

**Comment by ashu-dadhich** [comment]
![image](https://cloud.githubusercontent.com/assets/15179401/21166809/e6df01d4-c1cd-11e6-810d-d5df0b858514.png)
**this solves the problem**
But I think that's not the correct approach will come up with something better.
Thank you

**Comment by sandarumk** [comment]
This means what? Taking the email address to the next line?

**Comment by ashu-dadhich** [comment]
Yes here I added a \n after "email:" in information.xml. The problem is that it being considered as a continuous line. 

The problem with this approach is that it is disturbing the uniformity. Should I go with this or find an alternate solution.

**Comment by sandarumk** [comment]
I do not think we really have a solution for this, since this a wrapping issue. But there can be one which I didn't think of. If you can find an alternative solution, that would be great!

**Comment by ashu-dadhich** [comment]
I was going through android documentation and I found a attribute **android:hyphenationFrequency**

It solves the problem 

Please refer to this link https://developer.android.com/reference/android/widget/TextView.html

**Comment by ashu-dadhich** [comment]
I applied it here
`<?xml version="1.0" encoding="utf-8"?>

    <TextView xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@color/primary_text_default_material_dark"
        android:textSize="@dimen/abc_text_size_medium_material"
        android:layout_gravity="center_horizontal|right"
        android:background="@drawable/bg_textview_rounded_rectangle"
        android:padding="@dimen/textview_padding"
        android:scrollbars="vertical"
        android:fadeScrollbars="false"
        android:scrollHorizontally="true"
        android:hyphenationFrequency="none"
        android:layout_marginBottom="@dimen/activity_vertical_margin"
        android:autoLink="web|email"
        android:textColorLink="@color/text_color_link"
    />
`

**Comment by sandarumk** [comment]
If you set the hyphenation frequency as none to the whole text view, it would not add the hyphen where it is actually needed. But I guess that won't be a problem because we do not have long words which requires a hyphen and goes to the next line. But to make sure can you test with all the screens where the text view is used? If there are no more inconsistencies, you can send a PR.

**Comment by ashu-dadhich** [comment]
ok I will test it on all the screens and if no inconsistencies are found I will send a PR.
Thanks a lot :smile:

**Comment by ashu-dadhich** [comment]
I have tested on all screens and there are no inconsistencies but the problem is still persisting when we click on the mail link.
 
![image](https://cloud.githubusercontent.com/assets/15179401/21224283/783ba0be-c2f1-11e6-807c-6b4c502514b7.png)


**can you tell me where is the onclick method for the email**
as I couldn't find it in OtherStaffContent.java

**Comment by sandarumk** [comment]
It is done by android:autoLink attribute in the text view.

**Comment by ashu-dadhich** [comment]
Thanks. It was also a hyphenation problem but the mail will deliver to correct address.
I checked it 
**Sending PR**

**Comment by ashu-dadhich** [comment]
I have also uploaded a snapshot of the app logo issue which i discussed on slack please have a look at it
Thank you
