### ISSUE TITLE
Pressing "Search words..." in glossary will cause the toolbar to expand a lot

### ISSUE THREAD

**Issue by jeffsieu** [systers/PCSA-Android#335]
Before
![image](https://cloud.githubusercontent.com/assets/8487294/21253951/2c13ebc2-c39d-11e6-96b1-05d52b57ca5c.png)
After(expanded)
![image](https://cloud.githubusercontent.com/assets/8487294/21253967/3404093e-c39d-11e6-904e-9497002e71a5.png)

**Steps to recreate**
1. Press POLICIES AND GLOSSARY
2. Press GLOSSARY
3. Press "Search words..."

**Comment by pandilladivya** [comment]
@XOptimistixX 
This issue has already been reported in #309

**Comment by sandarumk** [comment]
Closing the issue since it is covered in #309
