### ISSUE TITLE
App crash in Circle of Trust Intro

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#338]
Following #303 
**Current Scenario**
There are two "Done" on the following screen. App is crashing when user clicks the Done (Center TextView).
<img src="https://cloud.githubusercontent.com/assets/13872065/21295856/14b607ba-c584-11e6-8689-89e224c5ea03.jpeg" width="200">

**Expected Behavior**
I believe providing two "Done" on same screen serving same purpose is not needed and Done(Textview) should be just for indication (not clickable).
 
 Since this is in accordance with PR #303 where I assumed that Done (Textview) is just for indication , I will like to correct this.

**Comment by sandarumk** [comment]
Sure. You can send a PR for this.

**Comment by sandarumk** [comment]
Any update?

**Comment by codingblazer** [comment]
@sandarumk PR sent.

**Comment by sandarumk** [comment]
Fixed with #346
