### ISSUE TITLE
SearchBar not visible in Glossary

### ISSUE THREAD

**Issue by sridharjajoo** [systers/PCSA-Android#339]
When we open up Glossary in POLICIES AND GLOSSARY ,the following is the situation of the screen:
![screenshot_2016-12-19-15-19-14-183_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/20684618/21308471/1fe7d830-c600-11e6-8233-727924df3edd.png)

But when we start to search something in the searchbar , the searchbar is hidden:
![screenshot_2016-12-19-15-20-22-571_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/20684618/21308551/6e4ef30a-c600-11e6-9410-4311a645252c.png)

So i would like to work on this issue by making the searchbar visible while someone is typing.

**Comment by sandarumk** [comment]
This issue is already reported before #309 . When you are reporting issues please go through the current issues first. It is good if you can go through the closed issues too to avoid duplication.
