### ISSUE TITLE
Comrade 6 contact number not shown.

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#34]
If we store numbers for all comrades as shown in image :
![screenshot_2016-02-09-00-03-09](https://cloud.githubusercontent.com/assets/8321130/12895156/e4b3fe4c-cec0-11e5-9708-728a111e19aa.png)

When we reopen the page to edit numbers , number for comrade 6 is not shown.

![screenshot_2016-02-09-00-03-18](https://cloud.githubusercontent.com/assets/8321130/12895173/03b06cfe-cec1-11e5-9aa0-88b4c3a6babd.png)

**Comment by sandarumk** [comment]
This issue is fixed with your PR.
