### ISSUE TITLE
Remove the redundant strings.xml files for API level and screen width

### ISSUE THREAD

**Issue by sandarumk** [systers/PCSA-Android#341]
There are two redundant strings.xml files for API version v21 and screen width 820dp. Hence the used string is the same, we do not need those two files. Remove them and add the string to the original strings.xml file.

**Comment by farbodsz** [comment]
I would like to work on this.

**Comment by sandarumk** [comment]
Sure you can go ahead. Please o through the READ ME and the linked best practices articles in the wiki. After you submit the PR, please comment the link of the PR in the claimed task as a comment and submit the task.
