### ISSUE TITLE
Wrong action bar title(BystanderInterventionFragment) should be Bystander Intervention.

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#345]
According to mockup Action bar is named BystanderInterventionFragment should be named Bystander Intervention in **Verbal with potential victim/Verbal with potential offender/ non verbal tactics for both**.

**Steps to reproduce:**
safety tools->bystander intervention->potential intervention strategies->verbal with potential victim.

**Snapshot:** 
![image](https://cloud.githubusercontent.com/assets/15179401/21539536/c4954b04-cdcd-11e6-9a3d-eb433a2a3f17.png)

**Comment by sandarumk** [comment]
You can fix this first and send a PR.

**Comment by sandarumk** [comment]
solved via #347
