### ISSUE TITLE
Next Button on Keyboard in Trustee Activity not works

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#349]
In trustee activity, on entering phone no. if we press next button on keyboard ( **->|** )the focus does not move to next edittext.
@sandarumk This is different from #218 #244 because that just worked when contact is picked from Contact picker.

<img src="https://cloud.githubusercontent.com/assets/13872065/21577204/ddaa630c-cf78-11e6-927c-ccbc3a2ae1e8.jpeg" height="200" >

**Expected Behavior** - If user press next on keyboard the focus should move to next nearest edittext like happens in all other apps. 
@sandarumk I have a fix for this. Can I work on this. :-)

**Comment by sandarumk** [comment]
yeah sure go ahead.

**Comment by sandarumk** [comment]
Fixed with #351
