### ISSUE TITLE
Name Box remains empty

### ISSUE THREAD

**Issue by reverie-ss** [systers/PCSA-Android#350]
If one saves the Name as empty in User Settings, it shows "Enter a valid name" toast.
![whatsapp image 2017-01-02 at 10 11 30 am 1](https://cloud.githubusercontent.com/assets/14177137/21584613/0b5d56d6-d0d4-11e6-9cee-c18e4c564e51.jpeg)
If it is clicked again, it shows an empty box.

![whatsapp image 2017-01-02 at 10 11 29 am](https://cloud.githubusercontent.com/assets/14177137/21584614/15502f7e-d0d4-11e6-94dd-9e3be3b662d4.jpeg)

Expected Behavior : It should populate the name

Should I work on it?

**Comment by sandarumk** [comment]
yes. You can go ahead. Before you fix and submit the PR, please make sure to go through the wiki article about PR best practices.

**Comment by reverie-ss** [comment]
Okay, i am on it !
This wiki article. Right?
[https://github.com/systers/PCSA-Android/wiki/PR-Best-Practices](url)

**Comment by sandarumk** [comment]
https://github.com/systers/FirstAide-Android/wiki/PR-Best-Practices

**Comment by reverie-ss** [comment]
Thank You!

**Comment by reverie-ss** [comment]
@sandarumk I have fixed the issue. Can you please check?

**Comment by sandarumk** [comment]
fixed with #353
