### ISSUE TITLE
New Ideas for further App Development

### ISSUE THREAD

**Issue by BaaniLeen** [systers/PCSA-Android#359]
@sandarumk  We can include a feature wherein the victim, in cases of emergency can contact one of the nearest Peace-Corps Volunteer (we need to implement an algorithm for the same which finds the nearest volunteer based on the location of the user as well as the volunteers) and the Volunteer (if the volunteer has turned on his availability on) can thereafter continuously track the location of the victim and thus, come to their rescue ASAP.
If approved, I would like to work on the same :)

**Comment by sandarumk** [comment]
We currently do not need this. There are Get Help Now and Circle of Trust where you can contact the Peace Corps officials in your country and contact your friends when you are in trouble. Will add this to the suggestion list to be discussed with Peacecorps.

**Comment by sandarumk** [comment]
One more thing, when you are adding an issue, please make its title reasonable and meaningful

**Comment by BaaniLeen** [comment]
Will surely keep that in mind the next time maam :)
Thank You.
