### ISSUE TITLE
The fragment is reloaded even if its displayed on clicking, in navigation drawer.

### ISSUE THREAD

**Issue by harshitagupta30** [systers/PCSA-Android#367]
**Actual Behaviour**
![videotogif_2017 01 23_00 00 40](https://cloud.githubusercontent.com/assets/12701036/22185075/a8128646-e104-11e6-9d7b-d08bb6f46d0f.gif)

**Expected Behaviour**
On clicking the same fragment it should not change.

@sandarumk I would like to work on it.

**Comment by sandarumk** [comment]
Sorry I missed this earlier. Will go through the code and let you know.

**Comment by sandarumk** [comment]
Yeah. This should be fixed. You can send a PR.

**Comment by harshitagupta30** [comment]
I also wanted to know that why are we backtracing the fragments in the stack in the app? Is there any special reason for that? Since we've limited memory and in almost all apps we don't do this.

**Comment by sandarumk** [comment]
If you have any more suggestions, please open up a separate issue and then let's discuss that there. Please include the issue/enhancement (better with a specific example). If you can please add your suggested fix as well. Do this as a best practice.

**Comment by harshitagupta30** [comment]
Apologies and thanks for letting know! :)
I'll make a new issue stating the entire scenario.

**Comment by reverie-ss** [comment]
@sandarumk 
I have figured out a solution to solve the bug
Should I send a PR?

**Comment by sandarumk** [comment]
@harshitagupta30 is already working on this. Please pick an issue not assigned to anyone else.

**Comment by sandarumk** [comment]
fixed via #378
