### ISSUE TITLE
calling signup-activity everytime after splashScreen. 

### ISSUE THREAD

**Issue by getsanjeev** [systers/PCSA-Android#369]
user login Boolean value can be always checked at splash screen using shared preferences. No need to check username not NULL in signupActivity everytime for launching mainActivity.

**Comment by sandarumk** [comment]
You can go ahead with this. But it seems to me that the user login boolean value is redundant and not used in anywhere. If so, there is no need of keeping that if we can do the same with the username. So remove it and shift the username check to the splash screen.

**Comment by getsanjeev** [comment]
Sure. I will do it.

**Comment by sandarumk** [comment]
Fixed with #373
