### ISSUE TITLE
Issues in Adding Comrade Numbers Interface

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#37]
There is a white strap at the bottom of the user interface.
See the screenshot
![screenshot_2016-02-10-00-07-43](https://cloud.githubusercontent.com/assets/754909/12926740/d236f5d8-cf8a-11e5-8249-57e920877468.png)

It's better to go back once the user pressed OK button.

Shall I start fixing these two issues?

**Comment by sandarumk** [comment]
Hi Chamika, I have already fixed the white strip issue. You can go ahead and implement the "going back to circle of trust"  after pressing OK. When implementing that please do not drop the toast message which is currently there.

**Comment by sandarumk** [comment]
Hi Chamika, Have you finished fixing the issue? If it is not started yet please let us know.

**Comment by chamika** [comment]
Hi, 
Activity close after OK button is fixed. See #42

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PCSA-Android/pull/42
