### ISSUE TITLE
Suggestion: Using volume or any hardware button to send help message.

### ISSUE THREAD

**Issue by ShailyTyagi** [systers/PCSA-Android#370]
Currently,if user needs help then he/she has to go to the circle of trust segment and then press the get help button. But, in emergency situations ,the user is panicked and hence it would be a great help if on the press of a single button the message is sent.
Also,we can put an option in settings where the user can choose if he/she wants to use the hardware button to send messages or not.
I think this is certainly a good feature.
I will be more than happy to work if this is approved. @sandarumk

**Comment by sandarumk** [comment]
Thank you very much for your suggestion. However we do not need this functionality. If you read previously closed issues, specially the ones tagged as suggestions, you would see that lot of similar ideas were reported.
