### ISSUE TITLE
Dialogs Goes Away on Orientation Change

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#376]
On changing the orientation in following screens, the dialog box closes itself -

1. Get Help now -> Contact Post Staff -> Contact PCO, Contact SSM, Contact SARL
2. Get Help Now -> Contact Other Post Staff ->Click Any button -> Contact Now 
3. Settings -> Name, Country 

<img src="https://cloud.githubusercontent.com/assets/13872065/22662025/922c98b0-eccd-11e6-8f66-653e7ddcfa81.gif" height="400" width="200">

@sandarumk Can i send PR for this ? Thanks

**Comment by sandarumk** [comment]
You can fix this with the landscape PR. I haven't reviewed it. So you can add the fix there.

**Comment by codingblazer** [comment]
@sandarumk Yeah sure. Will add commits soon.

**Comment by codingblazer** [comment]
Closing as fixed and merged via 77dabe4
