### ISSUE TITLE
Add comrade numbers by selecting from contacts

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#38]
**Improvement in adding comrade numbers**

Now comrade numbers have to enter manually by entering the phone number.
This is not user-friendly design and user might enter an incorrect number.

I think it's better to give the feature to select a phone number from the user contacts list.
Then the default icons for the circle of trust icons can be replaced with the contact picture. If a contact picture is not found, it can fill with the default icon. 

We have to add new permission (`android.permission.READ_CONTACTS`) to read contact lists.

**Comment by sandarumk** [comment]
Hi Chamika,
You can move forward with this. But first submit a mock up and a design as a comment before starting to implement, so we can review it and add suggestions and improvements. Keep in mind that the changes to the UI should be minimum. (A little change in Add number screen and no change apart from adding the contact pics as the default image in circle of trust.)
Dinu

**Comment by chamika** [comment]
Hi,
I will add some mock ups and post it here tomorrow.

**Comment by chamika** [comment]
Introduce new button "Add from contracts" to Comrades' number adding UI. As shown in red rectangle.
Once the user taps it, he will be navigated to default contact selection UI and upon selecting a contact, selected phone number will be filled automatically.
![screenshot_2016-02-13-22-47-34](https://cloud.githubusercontent.com/assets/754909/13029187/b7d9c008-d2aa-11e5-9b37-8c47f75a4d92.png)

After pressing OK button, the user will be navigated to Circle of Trust screen. If there are contact photos, the default icon will be replaced with the contact photo. See red rectangle
![screenshot_2016-02-13-22-47-38](https://cloud.githubusercontent.com/assets/754909/13029210/73d8b5f2-d2ab-11e5-8a99-9425a440c04e.png)

**Comment by sandarumk** [comment]
Is it possible to have the contact picture fit to the circle shape ? Can you change the color of "Add from contacts" icon to a color which matches more to the background color and post another pic so we can select which suits the best.
@calistus @Buddhiprabha @rosariorobinson  Do you have any suggestions apart from what I have suggested?

**Comment by Buddhiprabha** [comment]
Contact picture fits into a circle as per the design suggested. But there's a squared outline which I feel is unnecessary. You can remove that and add a white color border to the circle where the picture fits in.

**Comment by chamika** [comment]
By considering above comments, icon color is changed.
![screenshot_2016-02-15-23-58-28](https://cloud.githubusercontent.com/assets/754909/13057239/cbc01512-d440-11e5-9af6-87303eb04ec5.png)

Removed unnecessary squre border and added circular border with circular contact photos.
![screenshot_2016-02-15-23-58-16](https://cloud.githubusercontent.com/assets/754909/13057266/ee3d79cc-d440-11e5-98b2-770fba8fe2db.png)

**Comment by sandarumk** [comment]
Seems okay for me. @Buddhiprabha check whether this is what you suggested.

**Comment by Buddhiprabha** [comment]
@sandarumk Yes. @chamika you can proceed with this.

**Comment by chamika** [comment]
This is fixed.
Now comrades' number can be entered from contact selection
Circle of Trust shows photos if the phone numbers are already exist in the device contacts
Fixed issue if number is empty

See the PR #48

**Comment by sandarumk** [comment]
Merged.
