### ISSUE TITLE
Wrong Status Bar Color in CircleOfTrust and SignUp Activity

### ISSUE THREAD

**Issue by HimanshuS01** [systers/PCSA-Android#381]
Currently, the color of status bar in Circle Of Trust and Sign Up Activity is wrong as shown below.
![whatsapp image 2017-02-15 at 2 24 33 pm](https://cloud.githubusercontent.com/assets/18090596/22967015/ad0a6392-f38a-11e6-96e3-c638814c6aa7.jpeg)
![whatsapp image 2017-02-15 at 2 24 53 pm](https://cloud.githubusercontent.com/assets/18090596/22967014/ad09033a-f38a-11e6-9d53-71d00253daee.jpeg)

Fix - Color should be changed to dark green color.
@sandarumk Can i work on this. Thanks

**Comment by nehagup** [comment]
can i work on this?

**Comment by HimanshuS01** [comment]
hey @nehagup I have already solved this issue and it requires only a few line of fix. Once approved by @sandarumk I will send the PR. 
Thanks :)

**Comment by HimanshuS01** [comment]
@sandarumk can I send the PR for this issue?
_Thank you_

**Comment by sandarumk** [comment]
Can you add the images where this is correct along with the incorrect ones. Then it will be easy to compare.

**Comment by HimanshuS01** [comment]
**Incorrect status bar color in SignUp and CircleofTrust activity** 

![untitled-1](https://cloud.githubusercontent.com/assets/18090596/23329472/52e7c09e-fb5f-11e6-9cf1-c9b5a4fa8bcf.png)

**Correct one(in all activities)**

![device-2017-02-25-132931](https://cloud.githubusercontent.com/assets/18090596/23329483/7f023d94-fb5f-11e6-9028-0ab88696a08d.png)

@sandarumk Please review .
Thank you :)

**Comment by sandarumk** [comment]
yeah go ahead you can fix this.

**Comment by HimanshuS01** [comment]
sure @sandarumk .Will soon send the PR.
Thank you
