### ISSUE TITLE
Bugs at some places in an application

### ISSUE THREAD

**Issue by HimanshuS01** [systers/PCSA-Android#387]
1)Setting button at the top right corner is missing in SafetyPlanActivityClass which is present in the entire application.
![device-2017-03-02-130245](https://cloud.githubusercontent.com/assets/18090596/23497327/88d38656-ff48-11e6-81ba-09958b4f232c.png)
2)Title is not moving along with  the scrolling of list in **SafetyTools--> Unwanted attention** & in **SupportServices-->PeaceCopse MythBusters**. 
Fix:Title must also be scrolled up along with the list ,similar like in **SupportServices-->What To do after an assault-->Reporting Steps** to maintain uniformity in app.
Scrolling along with the  title should be like this:-
![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/18090596/23500614/b5d6f666-ff56-11e6-9981-967f5bbdd8b0.gif)
3)Color of the URL addresses in **GethelpNow** activities (PC saves anonymous helpline, Office of victim advocacy etc.)should be green as in other parts of an application.
![untitledsss-1](https://cloud.githubusercontent.com/assets/18090596/23501280/47935534-ff59-11e6-97ef-4ecacdee3002.png)
4)Color of the Floating action button in SupportServices should be **colorAccent** as per the google material design guidelines.
![device-2017-03-02-131111](https://cloud.githubusercontent.com/assets/18090596/23501551/4cca5c90-ff5a-11e6-8f88-ad447773fd4c.png)

@sandarumk If the above issues are an intended one, I would like to work on these. Can I send the PR for the same ?
Thank you . :)

**Comment by jacqueline8711** [comment]
@HimanshuS01 Hi, I think it's best if you make a separate issue for each bug since they are not related

**Comment by HimanshuS01** [comment]
hello @jacqueline8711 I think all of them are related to irregularities in UI. I thought it would be better to list them all here so in future any irregularity related bug can be report here.
However ,I will be creating separate commits for them if approved :)

**Comment by sandarumk** [comment]
@HimanshuS01, @jacqueline8711 is correct. Please report them separately so it will be easier to track down when PRs come and it will be also easier to distribute the task among lot of people.

**Comment by HimanshuS01** [comment]
sure @sandarumk . I got your point and will do the same. :)
Thanks

**Comment by HimanshuS01** [comment]
closing this issue now as I have reported the above issues individually in #392 #393 #394 #395
