### ISSUE TITLE
Settings button is missing in Trustees and SafetyPlanActivity Class

### ISSUE THREAD

**Issue by HimanshuS01** [systers/PCSA-Android#392]
Setting button at the top right corner is missing in **SafetyPlanActivityClass** and **Trustees.java** class which is present in the entire application.
**ScreenShots**
![untitled-1](https://cloud.githubusercontent.com/assets/18090596/23550034/fba3797e-0034-11e7-877e-76bbd8e5eb9c.png)

**Fix**
I have solved this issue while finding this bug, as it requires only to inflate the **settings.xml** file in **menu** directory , to the above mentioned activities.
```
 public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.settings,menu);
        return true;
    }

    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId())
        {
           case R.id.menu_settings:
                Intent intent=new Intent(this, UserSettingsActivity.class);
                startActivity(intent);
        }
        return true;
    }
```
 @sandarumk  Can I please create the PR for the same ?
_Thank You_

**Comment by sandarumk** [comment]
Should be fixed. Please send a PR.

**Comment by HimanshuS01** [comment]
Sure @sandarumk will soon send the PR :)

**Comment by pandilladivya** [comment]
@sandarumk @HimanshuS01 

Pardon me If I am wrong.
I dont think this is a bug.

If we observe, Settings Button is present in the ActionBar along with the hamburger icon in the left.
![1488716424288](https://cloud.githubusercontent.com/assets/16818129/23587206/2bfad54c-01cd-11e7-9117-7cc4f6b9521d.jpg)

In the Screens like UserSettings, Trustees, SafetyPlanActivity .. there is no hamburger icon in the left and there is no settings icon in the right. Instead there is a Back Button. 
![1488716362757](https://cloud.githubusercontent.com/assets/16818129/23587205/2bfa8772-01cd-11e7-987c-4c1023270b57.jpg)

I don't think Settings Button is missing..  I think it was made with an intention of making screens look consistent.

**Comment by HimanshuS01** [comment]
@pandilladivya 
The reason I feel there should be settings buttons in Safety Plan Activity is - In below screen, if you choose any button like Radar etc, you will find Settings button except in **SafetyPlan**
This I believe is the actual inconsistency.
<img src="https://cloud.githubusercontent.com/assets/18090596/23587450/348a94e0-01d2-11e7-9f7c-f6475400856f.jpeg" height="400" width="200">
Also I think it was not done intentionally. Everywhere in app, we have fragments in which settings icon came by default (as Main Activity has this icon in which these fragments are loaded)
  BUT 
Safety plan was made a separate activity in which settings icon didn't came by default and hence was missed by mistake. 
@pandilladivya  Thanks for the suggestion anyway :-)
