### ISSUE TITLE
Bug in URL address color in GetHelpNow activities

### ISSUE THREAD

**Issue by HimanshuS01** [systers/PCSA-Android#394]
Color of the URL addresses in **GethelpNow** activities (PC saves anonymous helpline, Office of victim advocacy etc.) should be green(**colorAccent**) as in other parts of an application.

**ScreenShot**
![untitledsss-1](https://cloud.githubusercontent.com/assets/18090596/23501280/47935534-ff59-11e6-97ef-4ecacdee3002.png)
This issue in in the reference of #387 

@sandarumk If you allow me to do so, I would like to work on this also ? :)
Thank you

**Comment by sandarumk** [comment]
you can go ahead with this.

**Comment by HimanshuS01** [comment]
sure @sandarumk will soon send the PR. :)
Thank you
