### ISSUE TITLE
FloatingActionButton color in SupportServices

### ISSUE THREAD

**Issue by HimanshuS01** [systers/PCSA-Android#395]
Color of the Floating action button in SupportServices should be **colorAccent** as per the google material design guidelines.

![device-2017-03-02-131111](https://cloud.githubusercontent.com/assets/18090596/23501551/4cca5c90-ff5a-11e6-8f88-ad447773fd4c.png)

This issue is in reference with #387 
@sandarumk Please review this issue  :)
_Thank you_

**Comment by swapsha96** [comment]
@HimanshuS01 I fixed it. What should I do now? Can you tell me the steps?

**Comment by HimanshuS01** [comment]
hey @swapsha96 Please wait for the mentor's @sandarumk reply to get this issue approved before assigning this issue you yourself so as to maintain the proper workflow.
And let @sandarumk decide, who can work on this issue .  :)
Thank you

**Comment by rohands** [comment]
@swapsha96 Please review the pull request guidelines before contributing next time. 
@HimanshuS01 Design issues are not entertained by the team since the design is approved by the PeaceCorps team before it's implemented.

**Comment by HimanshuS01** [comment]
@rohands Thanks for telling about this. :) 
I am closing this issue
