### ISSUE TITLE
Change TextView textColor

### ISSUE THREAD

**Issue by swapsha96** [systers/PCSA-Android#396]
White color is used everywhere but here content is in black.

![screenshot_20170303-185715 1](https://cloud.githubusercontent.com/assets/14021461/23552779/8c4413a4-0043-11e7-8996-544ceaaf4fd2.png)

@sandarumk Should I send PR for this?

**Comment by sandarumk** [comment]
Keep this as it is. We wanted this to differentiate from the rest.
