### ISSUE TITLE
Hardcoded dimensions, colors and integers in layouts.

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#40]
As per android best practices hardcoding must be avoided. All the dimensions must be placed in dimens.xml, colors in colors.xml and integers in integer.xml and strings in strings.xml. 

Currently strings have been placed in strings.xml , we need to do the same for dimensions, colors and integers.

**Comment by sandarumk** [comment]
This is a good initiative. Before you go forward with the development can you please comment the places where the changes are required.

**Comment by yatna** [comment]
Changes are required in the following layout files:
intro.xml, intro1.xml ,intro2.xml ,intro3.xml, textview.xml, fragment_circle_of_trust, fragment_main, fragment_safety_resources, activity_trustees, activity_reporting_confidentiality.

Eg in intro.xml
![image](https://cloud.githubusercontent.com/assets/8321130/13034420/22951770-d35b-11e5-9060-1a54732e9e55.png)

layout_height value must be put in dimens.xml,
layout_weight in integers.xml
textColor in colors.xml
text in strings.xml

**Comment by sandarumk** [comment]
Good. You Can move forward with this and submit a PR.

**Comment by yatna** [comment]
PR submitted #47

**Comment by sandarumk** [comment]
Merged
