### ISSUE TITLE
Enhancement: Using Butterknife for inflating views.

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#402]
**Summary**:
we can use butterknife for views injection for inflating views since it would make the code more tidy and easy to understand.

**Comment by sandarumk** [comment]
This has been suggested earlier as well. See closed pull requests, you will find one. So this has been previously discussed.  However, we do not need the butterknife integration at this point. We might consider this suggestion after the current product is production ready.

**Comment by sandarumk** [comment]
sug
