### ISSUE TITLE
Different Names in Toolbar Titles, Layouts, NavigationBar [Free] [Beginner]

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#413]
## Type 1 - Different names in Toolbar Title and corresponding button in layout

1. In below screen, the button says " Services after Sexual Assault" on opening which toolbar title says "Available Services" as shown below -

<img src="https://cloud.githubusercontent.com/assets/13872065/23689295/a97da2e2-03df-11e7-919a-40b562e13a51.jpeg" height="400" width="200">      <img src="https://cloud.githubusercontent.com/assets/13872065/23689016/ec8bbca6-03dd-11e7-9794-5f5cadbff65e.jpeg" height="400" width="200">

**Correct Version** - If we look at other buttons for ex - "Benefits of Seeking Staff Support", the title remains same as shown below -  

<img src="https://cloud.githubusercontent.com/assets/13872065/23689295/a97da2e2-03df-11e7-919a-40b562e13a51.jpeg" height="400" width="200">     <img src="https://cloud.githubusercontent.com/assets/13872065/23689240/62d05358-03df-11e7-95e4-29e54600719c.jpeg" height="400" width="200">

2. Same problem is present in Sexual Assault Awareness -> Was it Sexual Assault ?
3. Same problem is present in Sexual Assault Awareness -> Sexual Assault Common Questions
4. Same problem in Policies and Glossary -> Glossary 
5. Same problem in Policies and Glossary -> Further Resources

## Type 2 - Disparity in Names in Navigation Bar

6. In Navigation Bar -> Safety Tools , we have "Commonalities of Sexual Predators" but in layout it says "Tactics of Sexual Predators" as shown below -

<img src="https://cloud.githubusercontent.com/assets/13872065/23689012/ebd60230-03dd-11e7-820a-12cfdde45e35.jpeg" height="400" width="200">     <img src="https://cloud.githubusercontent.com/assets/13872065/23689015/ec7164d2-03dd-11e7-9ca9-504f25feb112.jpeg" height="400" width="200">

7. Same problem in Navigation Bar -> Safety Tools -> "Dealing with Unwanted Attention" while "Unwanted Attention" in buttons
 
@sandarumk I feel above issues if seem valid to you, can be taken by new contributors.

**Comment by priyankvex** [comment]
@codingblazer Can I work on this?

**Comment by codingblazer** [comment]
@priyankvex Lets just wait for @sandarumk confirmation. Then you may pick any one of them.

**Comment by codeb1ooded** [comment]
@sandarumk @codingblazer Can I work on Type 2 of this issue?

**Comment by priyankvex** [comment]
@codingblazer Cool! I will wait, then will work on type 1 if allowed. :smile:

**Comment by sandarumk** [comment]
@codingblazer  Thank you very much for reporting this. I made another issue to cover all the aspects in this issue. There seem to be a content mismatch which was also reported in some other issues as well. I asked to fix it in one place. But since this is being reported again and again, can we close this and move this to #431 so that we can find all the places where this content mismatch happens and decide on what to put on each step aligning to the content given by peace corps. The content document is attached at the said issue.

**Comment by codingblazer** [comment]
@sandarumk Yeah sure :-)
