### ISSUE TITLE
Navigation Bar not work for same index [Bug]

### ISSUE THREAD

**Issue by codingblazer** [systers/PCSA-Android#414]
Steps to generate the bug -

Step 1. Open Navigation Bar -> Open Any Expandable Heading (Let say "Safety Tools")-> Select any Sub Heading (Let say "Dealing with unwanted attention" which has index = 1)

Step 2. Open Navigation Bar again -> Open any other expandable heading (Let say "Support Services")-> Now open same index sub heading as in Step 1 (i.e index =1 which means "Services after Sexual Assault") => => Navigation won't work.
You may again go to some other subheading with same index 1 after this, it still won't work until some other index subheading is chosen.

**Demo** : [You Tube](https://youtu.be/QyjaUOhZpC4)

@sandarumk I have no assigned issues to work on. Can I send PR for this. Thanks.

**Comment by madhavrathi** [comment]
@codingblazer  can i work on this ?

**Comment by codingblazer** [comment]
Hey @madhavrathi I already have a solution for this. It won't be productive for you working out same solution. Please pick some free issue (there are many, check out 2nd page of issue list too :-)

**Comment by ashu-dadhich** [comment]
@codingblazer its working.
First I selected dealing with unwanted attention through nav bar
then 
selected Services after Sexual Assault and it navigated to it.
Tell if I am missing something here.

**Comment by codingblazer** [comment]
@top-gun007 Please update your develop branch :-)
you need to fetch the latest changes and rebase it.

**Comment by ashu-dadhich** [comment]
I did that already.

**Comment by HimanshuS01** [comment]
@top-gun007 Its a valid bug. I checked on my device too. Problem is occurring after some last PR's get merged. Please check it again .
Thanks :)

**Comment by ashu-dadhich** [comment]
https://www.youtube.com/watch?v=WRYFkOVzdy8
I am not saying its not a valid bug but I might be a possibility that the reason for it might be something else.

**Comment by codeb1ooded** [comment]
I am also encountering this issue @codingblazer

**Comment by codingblazer** [comment]
@top-gun007 I guess it could be some problem with your setup as its been confirmed by me as shown in [video](https://youtu.be/QyjaUOhZpC4) and by @HimanshuS01 @codeb1ooded @madhavrathi . Just to confirm this bug I am giving the reason for the bug -

In [Main Activity](https://github.com/systers/FirstAide-Android/blob/develop/app/src/main/java/com/peacecorps/pcsa/MainActivity.java) , the condition in line 147 & 148 is wrong.
```
if (lastExpandedGroup == groupPosition && lastChildExpandedGroup == childPosition) {
                 mDrawer.closeDrawer(GravityCompat.START);
              }
```
In this, since this is called when child listener function is called -> It means group is expanded since child is clicked -> lastGroupExpanded is the group of this clicked child only -> first condition will be always true.
Now whenever the 2nd condition inside "if statement" is true, navigation bar will close. This condition is true when lastchild index that was chosen equals current selected child index -> That's exactly the case for which I reported the bug.

**Comment by codingblazer** [comment]
@sandarumk Can you please confirm this bug once so I can proceed with it. Thanks :-)

**Comment by ashu-dadhich** [comment]
@codingblazer the bug is there should be corrected.
_Thank you_

**Comment by rohands** [comment]
@codingblazer go ahead with the implementation
