### ISSUE TITLE
arrow_left image view disappears on orientation change 

### ISSUE THREAD

**Issue by HimanshuS01** [systers/PCSA-Android#416]
The **arrow_left** image view in the **fragment_radar.xml** disappears on changing the device orientation.

**GIF for the issue**
![ezgif com-video-to-gif 8](https://cloud.githubusercontent.com/assets/18090596/23738104/1892afb4-04bd-11e7-8439-b32725e0d0d1.gif)
@sandarumk I think this seems valid to you and I have no assigned issue now.I would really like to work on this .
Can I send the PR?
_Thank You_ :)

**Comment by rohands** [comment]
Yes, you can go ahead. Please share the proposed solution here

**Comment by HimanshuS01** [comment]
As the current code in **RadarFrament.java** immediately hides the visibility of **prev_step** image view, at the time of loading of the RadarFrament.

 ```
        nextStep = (ImageView)rootView.findViewById(R.id.next_step);
        prevStep = (ImageView)rootView.findViewById(R.id.prev_step);
        final int[] steps = new int[]{R.string.step_1,R.string.step_2,R.string.step_3,R.string.step_4,R.string.step_5};
        stepIndicator = (TextView) rootView.findViewById(R.id.steps_text);
        stepIndicator.setText(Html.fromHtml(getString(steps[0])));
        prevStep.setVisibility(View.INVISIBLE) ;//In this line
```

So at the **STEP3** & **STEP4** when the orientation of the device changes, **RadarFrament** loads again and hides the **prev_step** image view.

**Fix:**
This issue has been solved by adding **prevStep.setVisibility(View.VISIBLE)**  line when the current selected page is either second or third.

![ezgif com-optimize 9](https://cloud.githubusercontent.com/assets/18090596/23801595/b2742fa8-05d6-11e7-97d5-c2bef1e57a4a.gif)

@rohands @sandarumk Can I send the Pr now?

**Comment by rohands** [comment]
Perfect. Go ahead!
