### ISSUE TITLE
Enhancement: User name should be in camel case.

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#418]
**Summary**
Currently the user name remains in the format in which user types since we are not dealing with usernames which contains certain notations and numerals we can use camel case to represent the Name of the user.

**Comment by sandarumk** [comment]
Can you provide an example for this?

**Comment by ashu-dadhich** [comment]
Like in this case the name is in small caps.
![image](https://cloud.githubusercontent.com/assets/15179401/23745243/862cb0d6-04dd-11e7-8eca-30971241c541.png)
eg if a user types "ashutosh dadhich" it should be "Ashutosh Dadhich" just like other popular apps.

**Comment by sandarumk** [comment]
It is not needed. This is not used for any authentication purposes and simply to log in (Until the MACC is done).
