### ISSUE TITLE
Hard coded dimens/text  

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#421]
**Summary**
In some instances the dimensions and strings are hard-coded should be moved to dimens.xml and strings.xml

**Comment by ashu-dadhich** [comment]
for eg. in activity_cycle_intro.xml
https://github.com/systers/FirstAide-Android/blob/develop/app/src/main/res/layout/activity_circle_intro.xml

**Comment by rohands** [comment]
Please review the entire codebase and make a list of all such instances and then continue.

**Comment by ashu-dadhich** [comment]
**Below is the list of files in which such instances are present**
activity_circle_intro

activity_trustees

fragment_assault_awareness

fragment_confidentiality

fragment_reporting_contact_other_staff

fragment_reporting_contact_post_staff

fragment_single_textview

fragment_support_services

fragment_was

intro4

navbar_listview_header

fragment_formatted_single_textview

fragment_radar

**Comment by ashu-dadhich** [comment]
Can I proceed @rohands ?
_Thank you_

**Comment by rohands** [comment]
Go ahead!

**Comment by abs51295** [comment]
@top-gun007 @rohands I think this is a lint issue and all the lint issues are already discussed in #222.

**Comment by sandarumk** [comment]
Sorry for not seeing this earlier. But please refrain from reporting lint issues as new issue. The lint issue list is for first time contributors.

**Comment by ashu-dadhich** [comment]
Actually the hard-coded dimes got added up due to latest merges and the there is no mention of hard-coded dimensions in lint issues @abs51295 only hard-coded strings is there.
https://himanshus01.github.io/LintIssues/index.html

**Comment by sandarumk** [comment]
Can we updated the lint issue list then?

**Comment by sandarumk** [comment]
Please update the lint issue list with the new set if you haven't already done so. Closing the issue as an duplicate.

**Comment by ashu-dadhich** [comment]
Already did that.
