### ISSUE TITLE
User who has logged in is shown at last in navigation bar rather it should be shown at top  .

### ISSUE THREAD

**Issue by pragyach** [systers/PCSA-Android#422]
![screenshot_2017-03-10-13-56-57](https://cloud.githubusercontent.com/assets/20520778/23787845/fb0336ac-0599-11e7-93db-67db1a5ed5ca.png)

**Comment by pragyach** [comment]
If this issue is not repoerted yet and if it seems to be valid i would like to work on it. @sandarumk

**Comment by sandarumk** [comment]
It is intentional.
