### ISSUE TITLE
getColor() depricated since API22

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#434]
**Summary**
Since API 22 getResources().getColor() is depricated. Since we have used it in various instances across the app I suggest we change it to.
`ContextCompat.getColor(context, R.color.your_color); `

**Refrence**
http://stackoverflow.com/questions/31590714/getcolorint-id-deprecated-on-android-6-0-marshmallow-api-23

**Comment by nitish1211** [comment]
@top-gun007 Can I work on this ?
It'll be a quick PR. :)

**Comment by abs51295** [comment]
@top-gun007 This is a lint issue and should be reported on #222.

**Comment by ashu-dadhich** [comment]
Don't worry @abs51295 It would be added to the lint list once @sandarumk says so.
Thanks for the concern 😄

**Comment by ashu-dadhich** [comment]
Closing since added in lint list in #222
