### ISSUE TITLE
Bug in ConfidentialityFragment

### ISSUE THREAD

**Issue by pandilladivya** [systers/PCSA-Android#438]
View is Ambiguous. Title is Displayed Twice in the Dialogue. 

![screenshot_2017-03-12-23-53-02](https://cloud.githubusercontent.com/assets/16818129/23834625/afbc930e-077f-11e7-8bbd-c060415e6819.png)

![screenshot_2017-03-12-23-53-05](https://cloud.githubusercontent.com/assets/16818129/23834626/afbe4096-077f-11e7-9469-276a571342f9.png)

![screenshot_2017-03-12-23-53-11](https://cloud.githubusercontent.com/assets/16818129/23834624/afbc5bfa-077f-11e7-8bca-2c6fa86d162f.png)

@sandarumk 
If this Bug is valid. I would like to work on this.
Thank you :)

**Comment by abs51295** [comment]
@pandilladivya It's working fine for me.

**Comment by pandilladivya** [comment]
@abs51295 

Can you please put a screenshot of this screen?

**Comment by abs51295** [comment]
![screenshot_20170313-020303](https://cloud.githubusercontent.com/assets/13438222/23835654/3bd52322-0791-11e7-9c98-3c7cae6833f0.png)

**Comment by pandilladivya** [comment]
@abs51295 What is the Android Version of your device?

**Comment by abs51295** [comment]
Android 7.0

**Comment by pandilladivya** [comment]
Yes. I've just tried it on my emulator, for Android Versions 7.1.1 and 6.0  its working fine.

![screenshot_1489351954](https://cloud.githubusercontent.com/assets/16818129/23835840/3b7bf466-0794-11e7-994a-48104e62c7cd.png)


**For Android Version 5.1**

![screenshot_2017-03-12-23-53-02](https://cloud.githubusercontent.com/assets/16818129/23835847/5d788566-0794-11e7-9325-af6e63d4ff4a.png)

**Comment by pandilladivya** [comment]
@sandarumk 

I've Debugged the code and solved this issue.
Can I send the PR for the same.

Thank You :)

**Comment by pandilladivya** [comment]
@sandarumk kindly review the issue and please let me know if it is a valid one.... 

Thank you :)

**Comment by sandarumk** [comment]
This is a valid issue.
