### ISSUE TITLE
Make the 'Learn More' link active

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#44]
There is an option to contact Office of General Inspector in the Other Staff option. On this page, there is a link given to learn more.

![screenshot_2016-02-14-23-28-58](https://cloud.githubusercontent.com/assets/8321130/13035309/d5516668-d372-11e5-8204-51afee9d2618.png)

The link is currently inactive.The link would serve useful if clicking on it opens up the destination page on our web browser, so that the users can get more information if they wish to. There will be no UI added and no existing UI will be changed, just an enhancement added.

**Comment by Buddhiprabha** [comment]
@yatna There are website links and/or e-mail addresses in all Other Staff and Support Options. I think all links can be activated: website links to open with a browser and e-mail addresses to open with a mail client. @rosariorobinson @calistus @sandarumk do you have any suggestions?

**Comment by yatna** [comment]
Yes , indeed , infact I was about to open a new issue regarding the email feature. Lets see what others feel. :-)

**Comment by sandarumk** [comment]
Yes @Buddhiprabha  you are correct. Both the active links and e mail support is needed. @calistus @rosariorobinson Do you have anymore suggestions regarding this? If not @yatna  can move forward with the implementation.

**Comment by yatna** [comment]
@sandarumk  Can you please guide me how to join the systers mailing list. I subscribed to systers-dev about a month ago, but I haven't yet recieved any confirmation. Am I missing something?

**Comment by sandarumk** [comment]
sure. These are all the systers mailing lists. http://www.systers.org/mailman/listinfo
Subscription happens almost same in all the mailing lists,
To subscribe to dev mailing list : http://www.systers.org/mailman/listinfo/systers-dev
You can fill the form and subscribe. If you followed these steps and didn't get an confirmation mail, it can be in your spam folder. Please check your spam folder.

**Comment by yatna** [comment]
Thanks :-) , the confirmation mail was in the promotions tab , hence did
not see it earlier.

**Comment by yatna** [comment]
PR submitted #46

**Comment by sandarumk** [comment]
merged.
