### ISSUE TITLE
Fragment not swapping when container has fragment from different group but having same childPosition 

### ISSUE THREAD

**Issue by sashafierce** [systers/PCSA-Android#445]
A sub-menu item can't be chosen if it has the same childPosition as the lastChildPosition (i.e. the fragment already in view )and swapping of this fragment is only possible from a sub-menu item with different childPosition.
Tested on API levels ranging from 19 to 23 .
@sandarumk Should I work on this issue?

**Comment by codingblazer** [comment]
Hy @sashafierce , this issue is duplicate of #414 . Please close this :-)
