### ISSUE TITLE
setDrawerListener method deprecated 

### ISSUE THREAD

**Issue by sashafierce** [systers/PCSA-Android#446]
According to [Official Documentation](https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#setDrawerListener(android.support.v4.widget.DrawerLayout.DrawerListener)) method is deprecated and following should be used instead -
```
addDrawerListener(DrawerListener) to add a listener
removeDrawerListener(DrawerListener) to remove a registered listener.
```

**Comment by abs51295** [comment]
@sashafierce There are several deprecated methods in this project which is a lint issue and should be reported in #222. Please do not create separate lint issues.

Thanks :)

**Comment by sashafierce** [comment]
Sure ! I couldn't find any seperate listed lint issues then.

**Comment by sandarumk** [comment]
Can you run a lint analysis and check the issue is there? You can update the original issue with a exported list if it deviates from the latest one. If this issue is not there, we can keep this issue open and continue working on this. If it is there, you can still work on the issue, but will close and mark this as a duplicate.

**Comment by sashafierce** [comment]
@sandarumk  Sure!

**Comment by sashafierce** [comment]
This issue is listed [here](http://akankshabhardwaj.me/inspections/Deprecation-index.html)
We can close this now.

**Comment by sashafierce** [comment]
@sandarumk should i send a PR fixing 'Deprecated API usage' lint issue which includes both setDrawerListener and getColor method upgrade ?

**Comment by sandarumk** [comment]
1. Do not reopen close issues if there is not an absolute necessity.
2. There is a separate list as I said in my earlier comment to discuss about the lint issues. Please follow that. All the communication regarding lint issues should happen in that thread so it will be easy to track.
