### ISSUE TITLE
PR Best Practices and some other text is not appearing as a link in readme.md

### ISSUE THREAD

**Issue by m-murad** [systers/PCSA-Android#449]
In `readme.md` PR Best Practices and click here should appear as a link. Instead its appearing as simple text with a link written next to it.

@sandarumk I will send a PR for this.

**Comment by ashu-dadhich** [comment]
@free4murad please follow the PR guidelines before sending a PR 😃 
https://github.com/systers/FirstAide-Android/wiki/PR-Best-Practices

**Comment by sandarumk** [comment]
fixed with #450
