### ISSUE TITLE
Rate and share the app 

### ISSUE THREAD

**Issue by GunpreetAhuja** [systers/PCSA-Android#457]
The features of sharing and rating the app can be added as they are in other apps. These can be placed on the right corner of the title bar.

**Comment by ashu-dadhich** [comment]
Hi @GunpreetAhuja how do you plan on accomplishing it?
You want to share the download link of the app right?

**Comment by sandarumk** [comment]
@GunpreetAhuja Welcome to FirstAide. This app is not for public use. It is only for peace corps volunteers. Hence we do not need a feature to share and rate the app. For more information please read the ReadME.

**Comment by GunpreetAhuja** [comment]
@sandarumk Thanku :)
I think we could still keep the rate app feature to maintain the quality and user satisfaction of the app.

**Comment by sandarumk** [comment]
Where would the ratings go? The app content is static without no backend. And since the audience is limited we would not want this to go on Play store. So how would we know the rating?
