### ISSUE TITLE
Add Emergency Contact Screen: Show Contact Name instead of Contact Number 

### ISSUE THREAD

**Issue by gesuindia** [systers/PCSA-Android#459]
Circle of Trustee > Add Emergency Contact 

Instead of showing contact number, the field could show the name of the contact person. That would be more helpful to the user in checking the entered contacts (before saving it). 

![emergency contact screen](https://cloud.githubusercontent.com/assets/25430731/25567769/d65a1eaa-2e12-11e7-885f-43c236a539ed.jpg)

@sandarumk If this is a valid issue, can I go ahead changing it?

**Comment by ashu-dadhich** [comment]
It was pointed out earlier too but it is the they wanted it to be. Please can go through the list of closed issue you might find it.

**Comment by gesuindia** [comment]
@top-gun007 

Okay, thanks. I will check it. 
Did they point any reason due  to which they want to go ahead with it?

**Comment by sandarumk** [comment]
@iri008 Please find the rationale in previous closed issues. Closing the issue.
