### ISSUE TITLE
Reporting Services: Adding a swipe icon instead of showing two cards at the same time. 

### ISSUE THREAD

**Issue by gesuindia** [systers/PCSA-Android#460]
Available Services > Reporting Services
The current screen looks like this. It looks messy and the lower most bar for "Learn about more" looks smaller in size than it should be in comparison with other elements. Also, instead of showing more than one card at a time on screen we could simply add a swipe icon for letting user swipe through the information. 

![reporting services_current](https://cloud.githubusercontent.com/assets/25430731/25567983/822f3078-2e16-11e7-8a04-16b700af4845.jpg)

We could make it look like this. We could also add more intuitive icons (e.g. ">") for swiping through the cards: 

![reporting services-postchanges](https://cloud.githubusercontent.com/assets/25430731/25567984/9673c7b0-2e16-11e7-8044-7c372b038f1c.jpg)

@sandarumk If this is a valid issue, please let me know if I could work on it.

**Comment by sandarumk** [comment]
I think there was a closed issue about this. Please go through the closed issue list.

**Comment by sandarumk** [comment]
Please find the rationale behind this in closed issues. There was an issue earlier as well suggesting the change.
