### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by till-tomorrow** [systers/PCSA-Android#470]
Update ###Opening and Running

As a open-source noob, the steps are a bit ambiguous while working on Windows OS. The 

> 3. Browse to the directory where you cloned (extracted the zip) FirstAide-Android App and take OK

should have the precise information that the project's _build.gradle_ should be imported for successful deployment. The step should be
**Browse to the root of the repository that you cloned and click on "OK"**

**Comment by r00pal** [comment]
@till-tomorrow Use ISSUE_TEMPLATE for creating an issue henceforth. Also, the language in the README.md is pretty clear. 
Closing this issue.
