### ISSUE TITLE
General Content Update

### ISSUE THREAD

**Issue by choquette33** [systers/PCSA-Android#50]
Adjust content to reflect this updated document: https://drive.google.com/open?id=0B8cm8EBZg0GaQy1CUkRUOXhWZUE

This document has a great table of contents that corresponds to H1 titles and H2 subtitles and the content that would be found in each section.

**Comment by AaskaShah** [comment]
Could I start implementing the content updates @choquette33 @sandarumk  ? 
To start with , In Reporting steps,should I add the contents in the steps or should I make steps clickable and add the description?

**Comment by sandarumk** [comment]
@AaskaShah Don't yet start on this. Meanwhile you can find any bugs in the current implementation and proceed with them.

**Comment by sandarumk** [comment]
@rosariorobinson Shall we plan and schedule these tasks for the next development sprint (preferably GSoC) ?
