### ISSUE TITLE
Add location details to Come get me if possible

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#51]
In the circle of trust, there is an option "Come get me" which sends a SMS message saying 
_"Come and get me. I need help getting home Safely. Call ASAP to get my Location.Sent through First Aide's Circle of Trust."_

This can be improved by adding location latitude and longitude by acquiring via GPS. If the user already enabled GPS and if the device can acquire accurate location it can be added to the SMS. Otherwise, the original SMS message can be sent saying _"Call ASAP to get my Location"_. 

It's possible to add Google maps URL so that user can open Google maps by tapping the SMS message link

**Comment by Buddhiprabha** [comment]
@calistus Did a GCI student work on GPS location?

**Comment by calistus** [comment]
Yes a student has worked on that.
Though for the GCI task, the app only displays the longitude and latitude.
@Chamika if you want to improve this, Instead of send the longitude and
latitude as a text message, It would be better if we can send the location
name.

**Comment by chamika** [comment]
I don't see any feature which retrieves device's location or usages of location permission in the `AndroidManifest.xml`

@calistus If we give the location name, it would be a certain area instead of exact position. So the receiver cannot accurately identify the location. If the receiver does not have a smartphone it is good to have the location name.
In my opinion adding location name and GPS locations would be a good solution.

**Comment by calistus** [comment]
Awesome. You can do that and send a PR

**Comment by chamika** [comment]
For retrieving location name, we need to do a network call which takes considerable time. Here we need to send the SMS message as soon as possible. Therefore, location name retrieval functionality is not added here. 
The process is like this,
When the user opens circle of trusts, it starts to search for GPS location, and if found it will be saved. When the user hit Help Me button if the location is already stored, it will be added to the SMS message and send. If not, the process is same as the existing flow which will send SMS message saying "Call Me"

See PR #66

**Comment by sandarumk** [comment]
Merged.
