### ISSUE TITLE
Add intro screens to Reporting Process.

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#53]
Intro screen can be added for Reporting Process same way as they are for Circle of Trust. These screens will appear to user the first time they click the option .

**Comment by yatna** [comment]
To maintain UI and code uniformity, I will use the same library as used in the earlier intro screens.

**Comment by sandarumk** [comment]
@rosariorobinson @Buddhiprabha What do you think on this?

**Comment by yatna** [comment]
@Buddhiprabha 
Can I submit a PR on this ?

**Comment by sandarumk** [comment]
@rosariorobinson @Buddhiprabha Can you please advice on this. I do not think we need intro screens for reporting process since it is fairly straightforward.

**Comment by Buddhiprabha** [comment]
@yatna @sandarumk Thanks for the suggestion. This is not required. Adding steps to Circle of Trust was done upon design change requests after mockup. Reporting process does not need this. Closing.
