### ISSUE TITLE
Save Location

### ISSUE THREAD

**Issue by scopeInfinity** [systers/PCSA-Android#62]
Under _Reporting Process/Contact Staff to Report_ changing location just changes contact info locally for an activity. However, Are we going to change location frequently? If not will it be good practices to save location in Shared Preferences.

**Comment by sandarumk** [comment]
Yeah. This is a good idea. You can implement and submit a PR on this.

**Comment by scopeInfinity** [comment]
@sandarumk I have created a PR #71
