### ISSUE TITLE
No Comrade

### ISSUE THREAD

**Issue by scopeInfinity** [systers/PCSA-Android#63]
Let's say Comrade list is Empty, then on clicking _Help Me_. It's simply showing _Message sent_ instead of showing _No Comrade Contact is Added_

**Comment by scopeInfinity** [comment]
Can I work on this?

**Comment by sandarumk** [comment]
This was earlier suggested by yatna (as I can remember) and I asked to send a PR. But the GitHub profile seems to be missing. Can you please wait few days (a week). So if that person faced a problem and back with the profile can submit the PR with that person's current work. If not you can submit the PR.

**Comment by scopeInfinity** [comment]
Ok! I can wait :smile:

**Comment by scopeInfinity** [comment]
Yes, the Issue already exists #52  and it's PR is also created #72
