### ISSUE TITLE
ContactPostStaff needs to be updated as in Mockup

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#64]
![amqovwo7i0oje7nnlvbnomjmm_k3cie1tljhglaos0mu 1](https://cloud.githubusercontent.com/assets/8949393/13397312/6101d12c-df1f-11e5-8191-cb6c73963d45.jpg)
<centre><strong> Current Implementation  </strong></centre>
![download](https://cloud.githubusercontent.com/assets/8949393/13397322/6c3b685a-df1f-11e5-95b4-b11faedbd241.png)
<center><strong> As in Mockup </strong></center>

Updates required : 

1. Button borders should change from white to black
2. Line divider below Get Help Now and above Post Staff
3. Link to "ContactOtherStaff" is shown as arrow next to one of the buttons in mockup while it's in the bottom in the current implementation

**Comment by Buddhiprabha** [comment]
Changes suggested are related to https://github.com/systers/PCSA-Android/issues/65
