### ISSUE TITLE
ContactOtherStaff needs to be updated as in Mockup

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#65]
![other](https://cloud.githubusercontent.com/assets/8949393/13397605/aecaf5ae-df20-11e5-8480-96643c59f557.jpg)
<strong>Current Implementation</strong>
![download 1](https://cloud.githubusercontent.com/assets/8949393/13397612/ba774e7a-df20-11e5-912c-042db5dcd217.png)
<strong> As in mockup </strong>

Updates required : 
1. Change button borders to black
2. Add a line divider below "Get Help Now" and above "Other Staff and ... "
3. Clean up the UI as in Mockup
4. Maybe have another arrow pointing to the left which will lead us back to the ContactPostStaffActivity

**Comment by Buddhiprabha** [comment]
@rohands 
1 - this is not required. All buttons in the app should have white borders.
3 - what are the specific changes you intend to implement?
4 - there is already an arrow which leads back to ContactPostStaffActivity. Are you going to change this? If so, how?

**Comment by rohands** [comment]
@Buddhiprabha 
Points 1 and 2 mentioned by me are in accordance with your mockup. 
For 
4 - In the mockup design for ContactPostStaff, there is an arrow pointing to the right which leads to ContactOtherStaff. But in the mockup design for ContactOtherStaff as shown above, there is no way to go back to the ContactPostStaff. 
    Therefore, I asked whether it would be a good idea to have an arrow pointing to the left which goes back to ContactPostStaff?

Here is the mockup design of ContactPostStaff, please note the <strong>arrow pointing to the right. </strong> 
![download](https://cloud.githubusercontent.com/assets/8949393/13398405/1e067e0e-df24-11e5-8a18-dbfcdf000a38.png)

Regarding 3 (cleaning the UI as shown in mockup), 
There are certain minute changes like, 
1. "Get Help Now" should fall one step below
2. There should be a divider seperating "Get Help Now" and "Other Staff and Support Options"
3. The order of buttons shown are different in the mockup
4. And if approved, maybe we can have the arrow leading back to ContactPostStaff in a similar way as shown in the mockup for ContactPostStaff

**Comment by Buddhiprabha** [comment]
@rohands 
4 - although it is not there in the mockup, in the actual implementation, at the bottom of the both pages (Post Staff and Other Staff) there are links to go to each other. If you need to change this by adding a button which will exactly look like the button in the Post Staff page in the mockup, please go ahead and do so. Please add a similar button to the Other Staff page as well.

2 - You can drop this for the time being as it can cause the UIs to be inconsistent. Therefore you do not need to add a line or to make "Get Help Now" fall one step below.

Regarding the order of the items - The order was changed after the mockup. The current implementation has the correct order and therefore no need to change the order. We are still in the process of updating the mockup.

**Comment by rohands** [comment]
@Buddhiprabha 
I'll go ahead with making the arrows as shown in mockup and implement the same in the other activity (other staff) too, thank you.

**Comment by sandarumk** [comment]
@Buddhiprabha is it okay to change the button? it will remove the wording that it direct to the post staff and vice versa?

**Comment by Buddhiprabha** [comment]
@sandarumk yes it is okay. The mockup shows the correct design in that case.

**Comment by sandarumk** [comment]
Ok great! :)

**Comment by sandarumk** [comment]
merged.
