### ISSUE TITLE
Displays the same content in Reporting services

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#67]
If the user navigates to Reporting Process -> Reporting Types from the application, the horizontally scrollable view shows the same content twice. 
See attached screenshots

![screenshot_2016-02-29-20-59-52](https://cloud.githubusercontent.com/assets/754909/13399390/11df782e-df29-11e5-8b70-53dc7e67fc2c.png)

![screenshot_2016-02-29-20-59-59](https://cloud.githubusercontent.com/assets/754909/13399389/11ddddd4-df29-11e5-900e-fc7ba386b574.png)

**Comment by sandarumk** [comment]
@Buddhiprabha Can you please clarify this issue? Is there any specific requirement that it is made in this way? Or can the repeated page be removed.

**Comment by Buddhiprabha** [comment]
@chamika yes this is an issue. Thanks for reporting. There has to be two screens. Do not remove the second screen, I will add the contents.

**Comment by chamika** [comment]
@Buddhiprabha 
If you like, I can add if it you direct me to the content or supply the content

**Comment by Buddhiprabha** [comment]
The content was available in strings.xml. Corrected the reference.

**Comment by Buddhiprabha** [comment]
Fixed with https://github.com/systers/PCSA-Android/pull/70
