### ISSUE TITLE
Circle of Trust introduction UI issues

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#68]
In the 2nd page, text color is not matching with the background which makes unable to read in small screens.
Spelling error in "Prees" -> "Press"
![screenshot_2016-02-29-21-20-22](https://cloud.githubusercontent.com/assets/754909/13399870/4f74c386-df2b-11e5-95b7-f051f164545c.png)

In the last page, Picture has white background
![screenshot_2016-02-29-21-14-25](https://cloud.githubusercontent.com/assets/754909/13399709/a58962b4-df2a-11e5-9193-208248e812c6.png)

**Comment by sandarumk** [comment]
Hi Chamika, What are your suggested improvements in these two issues?

**Comment by chamika** [comment]
Text color or size can be changed so that it is more visible to the user.
That image can be changed to new image like
![image](https://cloud.githubusercontent.com/assets/754909/13402909/8096fbca-df38-11e5-8ccd-ea24a038cc1a.png)

or

![image](https://cloud.githubusercontent.com/assets/754909/13402922/90dd9688-df38-11e5-9cdc-6488a91ed798.png)

If the hand icon is required, we can remove white background

**Comment by sandarumk** [comment]
You can change the text size to match the last page. Correct the spelling mistake and the grammar error. ("When you are feeling insecure or need comrades' attention") and submit a PR for now. 
@Buddhiprabha @calistus What do you think about the new image? is it better like this or removing the white background of the like icon is good?

**Comment by chamika** [comment]
2nd page issues are fixed.
See PR #69

**Comment by calistus** [comment]
It will be better if we remove the white background
