### ISSUE TITLE
Option icon not clickable

### ISSUE THREAD

**Issue by AaskaShah** [systers/PCSA-Android#74]
The option icon here on the left of the page heading is useless, are there any options which are needed to be added by making it clickable?

![screenshot from 2016-03-01 02 16 30](https://cloud.githubusercontent.com/assets/11875217/13409249/1ac1d778-df58-11e5-83a7-9da3d1b66078.png)

**Comment by sandarumk** [comment]
Thank you for reporting. We will look into this.

**Comment by AaskaShah** [comment]
I would like to work on it if this needs to be implemented :)

**Comment by sandarumk** [comment]
Thank you for your interest. We are going to keep this as it is. It may change in future with the updates for the design in next development cycle.
