### ISSUE TITLE
Help Me dialog box not implemented as in mockup.pdf

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#76]
In mockup.pdf :
![screenshot from 2016-03-01 04 08 05](https://cloud.githubusercontent.com/assets/8321130/13411502/5c8a397e-df63-11e5-9ecf-56cf152ddba0.png)

Actual :
![screenshot_2016-03-01-04-05-26](https://cloud.githubusercontent.com/assets/8321130/13411508/657df8fe-df63-11e5-80a7-cf8fc2e60afd.png)

Here are the changes I propose to do:
1. Remove the cancel button, since it is of no use , dialog box can be canceled by clicking anywhere in the background.
2. Remove the heading "Select a request" , as options are self explanatory.
3. Remove the radio buttons, since the text is itself clickable and radio buttons serve on real purpose in this case.
4. Insert dividers between options as in mockup.pdf.

**Comment by sandarumk** [comment]
@yatna Please note that the mockup is outdated and we are in the process of updating. The app contains the tweaked version of this screen.
