### ISSUE TITLE
Using beeps and sounds in Circle of Trust .

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#77]
We can make the application more responsive by adding sound effects at appropriate places.
E.g. the app will generate a alert beep if message sending fails after pressing help me. Similarly there can be a success beep if messages are sent successfully .
This will help the user in case he/she forgets to see the toast  displayed after pressing Help Me button.

**Comment by sandarumk** [comment]
Thank you for your suggestion. We will keep this in mind when taking decisions for the new development cycle. Please use the issue list to suggest the issues/enhancements in already developed sections. You can use the mailing list with [PCSA] tag to suggest these.
