### ISSUE TITLE
Add functionality to "Get Help Now" button in MainActivity

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#81]
Since it is already implemented, 
Can I write an intent which starts ContactPostStaffActivity on clicking Get Help Now button in MainActivity?

![screenshot_2016-03-02-03-14-24](https://cloud.githubusercontent.com/assets/8949393/13443006/f901b78e-e024-11e5-903a-51453b8670be.png)
Currently says no functionality

**Comment by sandarumk** [comment]
@Buddhiprabha should this lead to the implemented Get Help Now?

**Comment by rohands** [comment]
@sandarumk 
Any update on this?

**Comment by Buddhiprabha** [comment]
@sandarumk Yes. @rohands You may proceed.

**Comment by sandarumk** [comment]
Merged.
