### ISSUE TITLE
Rearranging Comrade Numbers

### ISSUE THREAD

**Issue by scopeInfinity** [systers/PCSA-Android#88]
![Screenshot](https://cloud.githubusercontent.com/assets/9819066/13499677/6141125c-e185-11e5-971a-8ff55603f614.png)

Here, It will look nice if on submitting, empty gaps in middle show be ignored before saving.

![Screenshot](https://cloud.githubusercontent.com/assets/9819066/13499771/a4a4e5d2-e185-11e5-9872-2e8eb3c21dee.png)

And it look like this on opening again

**Comment by sandarumk** [comment]
@rosariorobinson @Buddhiprabha @calistus I would like to know your ideas regarding this issue. My idea is it seems like a valid one to rearrange since we haven't decide priorities on these.

**Comment by sandarumk** [comment]
We may be introduce priorities. So for the time being we will keep this as a suggestion and discuss in our next design meetings.
