### ISSUE TITLE
Opening and sending email when the email id clicked

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#89]
Enabling and redirecting to gmail (or yahoo) with recievers email in it 
Body can be added by user and mail sent

![screenshot_2016-03-03-21-48-42_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/14356938/13500916/96a005de-e18a-11e5-8429-5b4211c7129d.png)
![screenshot_2016-03-03-21-48-49_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/14356938/13500917/96a29060-e18a-11e5-9073-021337415531.png)

**Comment by scopeInfinity** [comment]
Issue #44 is already there with same thing I guess, Check PR #46

**Comment by AkankshaBodhankar** [comment]
Ohh yes thank you :-)
