### ISSUE TITLE
Comrades Phone Ring when Receive SMS

### ISSUE THREAD

**Issue by scopeInfinity** [systers/PCSA-Android#90]
Idea : Suppose I press 'Help Me' then SMS sends to my comrades list.
Nowadays many person ignores SMS thinking of that they will read it later(Or doesn't give much effort to read a SMS).

Solution : What about if Comrade will have PCSA-Android app install in his/her phone, a Ring can be generated to notify user on receiving SMS sended by PCSA-Android.

**Comment by sandarumk** [comment]
Thank you for your suggestion. We will keep this in mind for the discussions in the next development cycle. Please use the issue list to report problems of the already developed sections. You can discuss these type of improvements in the mailing list. It will be easy for us if you use [PCSA] tag at the beginning of the title.
