### ISSUE TITLE
Implementation of "Confidentiality", "Safety Resources" and "Helping Others

### ISSUE THREAD

**Issue by InsectiousApp** [systers/PCSA-Android#92]
@Buddhiprabha @sandarumk @rosariorobinson @shruti-gupta 
I would like to implement the following parts of the applications which are yet to be done as specified in the mockup 

1. Safety Resources (Pg. 10)
2. Confidentiality (Pg 11)
3. Helping (Pg 12).

I  am very much interested in implementing these. And i would like to present you the UI i am going to make in advance if you think it would be more helpful. Waiting for your sugggestions
Thanking you
Chetan mann

**Comment by sandarumk** [comment]
@InsectiousApp Thank you for your interest. These will be implemented in our next development cycle. The functionalities of these features which are not implemented is not finalized yet.  Please use mailing list for these kind of suggestions. Please use issues in the github repo to report t6he bugs and new suggestions in the current development.
