### ISSUE TITLE
Make comrade icon clickable 

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#93]
When the comrade icon is clicked the phonenumber and possibly name can be displayed

**Comment by AkankshaBodhankar** [comment]
@sandarumk  @Buddhiprabha can i go ahead with this

**Comment by sandarumk** [comment]
This  is previously suggested and rejected.

**Comment by sandarumk** [comment]
Please refer https://github.com/systers/PCSA-Android/pull/36
