### ISSUE TITLE
Option for phone call to the comrades 

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-Android#95]
Along with the select request message phone call also can be made to the comrades
At a time six phone calls cannot be made so,
The phone calls can be made in order like comrade1 then comrade2 so on...(if one comrade doesn't lift then next comrade so on.....)

**Comment by medhach** [comment]
We can also prioritize the comrades, and the calls can be made as per the priorities

**Comment by sandarumk** [comment]
Thank you for the suggestion. We will note them and discuss about them and their need of implementing in the next development cycle. Please use the mailing list with the tag [PCSA] in the front for these type of suggestions. Use the issue list to suggest improvements and bugs in already developed sections(functionalities).

**Comment by AkankshaBodhankar** [comment]
Okay Thank you :-)
