### ISSUE TITLE
Adjust Reporting types UI for tablet mode

### ISSUE THREAD

**Issue by AaskaShah** [systers/PCSA-Android#98]
The reporting types page looks like this on tablets:

![screenshot from 2016-03-05 19 01 14](https://cloud.githubusercontent.com/assets/11875217/13548954/0a7bb4ba-e322-11e5-9891-a9665df9b572.png)

This could be changed to something like -
![screenshot from 2016-03-05 22 42 13](https://cloud.githubusercontent.com/assets/11875217/13549092/b7bfd820-e324-11e5-8212-5223ec12da9b.png)

Can I go ahead and send a PR?

**Comment by sandarumk** [comment]
Similar to your previous issue, We made this an general issue which will be addressed later. Thank you very much for reporting.

**Comment by sandarumk** [comment]
duplicated in #126 and made a general issue.
