### ISSUE TITLE
Shift circle of trust to center in tablet mode

### ISSUE THREAD

**Issue by AaskaShah** [systers/PCSA-Android#99]
Circle of trust looks like this:

![screenshot from 2016-03-05 20 10 30_before](https://cloud.githubusercontent.com/assets/11875217/13549130/b2711144-e325-11e5-9cfa-74c073f576a0.png)

This could be made something like: 
![screenshot from 2016-03-05 18 48 51](https://cloud.githubusercontent.com/assets/11875217/13549133/b3e3ba4a-e325-11e5-9d79-4d2eaa5108c6.png)

Can I submit a PR for this?

**Comment by sandarumk** [comment]
This seems a general issue. The UI doesn't adapt to the different screen sizes. Thank you for reporting. We will fix this in next development. UI may change, hence the development effort will be wasted. To revisit this, I created a general issue and put it on hold

**Comment by sandarumk** [comment]
#126 is created to reflect this and several other UI issues regarding the screen sizes.
